# SPDX-FileCopyrightText: 2025-present cerilloderek <derek@cerillo.bio>
#
from .base_plate_reader import CerilloBasePlateReader
from .stratus import StratusReader
from .rayo import RayoReader, MotorCommand, MotorNamedCommand, MotorStepCommand
from .cdcl.cdcl import (
    CDCLParseError,
    CDCLParser,
    CDCLResponse,
    CDCLCommand,
    PlateReaderModeCalculator,
)
from .cdcl.experiment_builder import (
    ExperimentBuilder,
    PlateTemplateBuilder,
)
from .cdcl.prefixes import (
    GenericInstructionPrefixes,
    PlateReaderSpecificInstructionPrefixes,
    CanopySpecificInstructionPrefixes,
    PlateReaderInstructionPrefixes,
    GenericResponsePrefixes,
    PlateReaderSpecificResponsePrefixes,
    StratusResponsePrefixes,
    StartCommandPrefixes,
    PlateTemplateMetadataPrefixes,
    PlateTemplatePrefixes,
    PlateTreatmentType,
    WellBottomType,
    PlateLidType,
    ExperimentType,
)
from .cdcl.start_commands import (
    StartCommand,
    ResetStartCommand,
    SetIntervalCommand,
    SetDurationCommand,
    SetModeCommand,
    SetExperimentNameCommand,
    SetExperimentIDCommand,
    SetUserCommand,
    SetExperimentTypeCommand,
    SetQueueCommand,
    ExecuteStartCommand,
    PlateTemplateCommand,
    SetPlateRowsCommand,
    SetPlateColsCommand,
    SetWellDiameterCommand,
    SetWellHeightCommand,
    SetWellVolumeCommand,
    SetPlateTreatmentCommand,
    SetWellBottomCommand,
    SetPlateLidCommand,
    AssignDetectorToWellCommand,
    SetPlateManufacturerCommand,
    SetPlateModelCommand,
    SetPlateTemplateNameCommand,
    AddPlateLayoutLineCommand,
)

__all__ = [
    "CerilloBasePlateReader",
    "StratusReader",
    "RayoReader",
    "MotorCommand",
    "MotorNamedCommand",
    "MotorStepCommand",
    # CDCL core
    "CDCLParseError",
    "CDCLParser",
    "CDCLResponse",
    "CDCLCommand",
    "PlateReaderModeCalculator",
    # Builders
    "ExperimentBuilder",
    "PlateTemplateBuilder",
    # Prefixes / enums
    "GenericInstructionPrefixes",
    "PlateReaderSpecificInstructionPrefixes",
    "CanopySpecificInstructionPrefixes",
    "PlateReaderInstructionPrefixes",
    "GenericResponsePrefixes",
    "PlateReaderSpecificResponsePrefixes",
    "StratusResponsePrefixes",
    "StartCommandPrefixes",
    "PlateTemplateMetadataPrefixes",
    "PlateTemplatePrefixes",
    "PlateTreatmentType",
    "WellBottomType",
    "PlateLidType",
    "ExperimentType",
    # Start command helpers
    "StartCommand",
    "ResetStartCommand",
    "SetIntervalCommand",
    "SetDurationCommand",
    "SetModeCommand",
    "SetExperimentNameCommand",
    "SetExperimentIDCommand",
    "SetUserCommand",
    "SetExperimentTypeCommand",
    "SetQueueCommand",
    "ExecuteStartCommand",
    "PlateTemplateCommand",
    "SetPlateRowsCommand",
    "SetPlateColsCommand",
    "SetWellDiameterCommand",
    "SetWellHeightCommand",
    "SetWellVolumeCommand",
    "SetPlateTreatmentCommand",
    "SetWellBottomCommand",
    "SetPlateLidCommand",
    "AssignDetectorToWellCommand",
    "SetPlateManufacturerCommand",
    "SetPlateModelCommand",
    "SetPlateTemplateNameCommand",
    "AddPlateLayoutLineCommand",
]
