import os
import pandas as pd

MISSION_INFO = [
    {
        "mission": 2,
        "pass": 1,
        "RFI": "High",
        "heading": "225",
        "incidence_angle": "58",
        "name": "v02_2",
        "deployment": "Sigismund",
        "targets_list": "Sigismund.Targets.txt",
        "filename": "v02_2_1_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 2,
        "pass": 2,
        "RFI": "Low",
        "heading": "135",
        "incidence_angle": "58",
        "name": "v02_2",
        "deployment": "Sigismund",
        "targets_list": "Sigismund.Targets.txt",
        "filename": "v02_2_2_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 2,
        "pass": 3,
        "RFI": "High",
        "heading": "225",
        "incidence_angle": "58",
        "name": "v02_2",
        "deployment": "Sigismund",
        "targets_list": "Sigismund.Targets.txt",
        "filename": "v02_2_3_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 2,
        "pass": 4,
        "RFI": "Low",
        "heading": "135",
        "incidence_angle": "58",
        "name": "v02_2",
        "deployment": "Sigismund",
        "targets_list": "Sigismund.Targets.txt",
        "filename": "v02_2_4_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 2,
        "pass": 5,
        "RFI": "High",
        "heading": "230",
        "incidence_angle": "58",
        "name": "v02_2",
        "deployment": "Sigismund",
        "targets_list": "Sigismund.Targets.txt",
        "filename": "v02_2_5_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 2,
        "pass": 6,
        "RFI": "High",
        "heading": "230",
        "incidence_angle": "58",
        "name": "v02_2",
        "deployment": "Sigismund",
        "targets_list": "Sigismund.Targets.txt",
        "filename": "v02_2_6_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 3,
        "pass": 1,
        "RFI": "High",
        "heading": "225",
        "incidence_angle": "58",
        "name": "v02_3",
        "deployment": "Karl",
        "targets_list": "Karl.Targets.txt",
        "filename": "v02_3_1_2.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 3,
        "pass": 2,
        "RFI": "Low",
        "heading": "135",
        "incidence_angle": "58",
        "name": "v02_3",
        "deployment": "Karl",
        "targets_list": "Karl.Targets.txt",
        "filename": "v02_3_2_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 3,
        "pass": 3,
        "RFI": "High",
        "heading": "225",
        "incidence_angle": "58",
        "name": "v02_3",
        "deployment": "Karl",
        "targets_list": "Karl.Targets.txt",
        "filename": "v02_3_3_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 3,
        "pass": 4,
        "RFI": "Low",
        "heading": "135",
        "incidence_angle": "58",
        "name": "v02_3",
        "deployment": "Karl",
        "targets_list": "Karl.Targets.txt",
        "filename": "v02_3_4_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 3,
        "pass": 5,
        "RFI": "High",
        "heading": "230",
        "incidence_angle": "58",
        "name": "v02_3",
        "deployment": "Karl",
        "targets_list": "Karl.Targets.txt",
        "filename": "v02_3_5_2.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 3,
        "pass": 6,
        "RFI": "High",
        "heading": "230",
        "incidence_angle": "58",
        "name": "v02_3",
        "deployment": "Karl",
        "targets_list": "Karl.Targets.txt",
        "filename": "v02_3_6_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 4,
        "pass": 1,
        "RFI": "High",
        "heading": "225",
        "incidence_angle": "58",
        "name": "v02_4",
        "deployment": "Fredrik",
        "targets_list": "Fredrik.Targets.txt",
        "filename": "v02_4_1_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 4,
        "pass": 2,
        "RFI": "Low",
        "heading": "135",
        "incidence_angle": "58",
        "name": "v02_4",
        "deployment": "Fredrik",
        "targets_list": "Fredrik.Targets.txt",
        "filename": "v02_4_2_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 4,
        "pass": 3,
        "RFI": "High",
        "heading": "225",
        "incidence_angle": "58",
        "name": "v02_4",
        "deployment": "Fredrik",
        "targets_list": "Fredrik.Targets.txt",
        "filename": "v02_4_3_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 4,
        "pass": 4,
        "RFI": "Low",
        "heading": "135",
        "incidence_angle": "58",
        "name": "v02_4",
        "deployment": "Fredrik",
        "targets_list": "Fredrik.Targets.txt",
        "filename": "v02_4_4_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 4,
        "pass": 5,
        "RFI": "High",
        "heading": "230",
        "incidence_angle": "58",
        "name": "v02_4",
        "deployment": "Fredrik",
        "targets_list": "Fredrik.Targets.txt",
        "filename": "v02_4_5_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 4,
        "pass": 6,
        "RFI": "High",
        "heading": "230",
        "incidence_angle": "58",
        "name": "v02_4",
        "deployment": "Fredrik",
        "targets_list": "Fredrik.Targets.txt",
        "filename": "v02_4_6_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 5,
        "pass": 1,
        "RFI": "High",
        "heading": "225",
        "incidence_angle": "58",
        "name": "v02_5",
        "deployment": "Adolf_Fredrik",
        "targets_list": "Adolf_Fredrik.Targets.txt",
        "filename": "v02_5_1_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 5,
        "pass": 2,
        "RFI": "Low",
        "heading": "135",
        "incidence_angle": "58",
        "name": "v02_5",
        "deployment": "Adolf_Fredrik",
        "targets_list": "Adolf_Fredrik.Targets.txt",
        "filename": "v02_5_2_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 5,
        "pass": 3,
        "RFI": "High",
        "heading": "225",
        "incidence_angle": "58",
        "name": "v02_5",
        "deployment": "Adolf_Fredrik",
        "targets_list": "Adolf_Fredrik.Targets.txt",
        "filename": "v02_5_3_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 5,
        "pass": 4,
        "RFI": "Low",
        "heading": "135",
        "incidence_angle": "58",
        "name": "v02_5",
        "deployment": "Adolf_Fredrik",
        "targets_list": "Adolf_Fredrik.Targets.txt",
        "filename": "v02_5_4_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 5,
        "pass": 5,
        "RFI": "High",
        "heading": "230",
        "incidence_angle": "58",
        "name": "v02_5",
        "deployment": "Adolf_Fredrik",
        "targets_list": "Adolf_Fredrik.Targets.txt",
        "filename": "v02_5_5_1.a.Fbp.RFcorr.Geo.Magn",
    },
    {
        "mission": 5,
        "pass": 6,
        "RFI": "High",
        "heading": "230",
        "incidence_angle": "58",
        "name": "v02_5",
        "deployment": "Adolf_Fredrik",
        "targets_list": "Adolf_Fredrik.Targets.txt",
        "filename": "v02_5_6_1.a.Fbp.RFcorr.Geo.Magn",
    },
]

MISSION_INFO = pd.DataFrame(MISSION_INFO)
MISSION_INFO = MISSION_INFO.set_index(["mission", "pass"])
