# coding: utf-8

"""
    CogStack Model Serve APIs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cms_client.api.training_api import TrainingApi


class TestTrainingApi(unittest.TestCase):
    """TrainingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TrainingApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_training(self) -> None:
        """Test case for cancel_training

        Cancel Training
        """
        pass

    def test_get_evaluation_with_trainer_export(self) -> None:
        """Test case for get_evaluation_with_trainer_export

        Get Evaluation With Trainer Export
        """
        pass

    def test_train_eval_info(self) -> None:
        """Test case for train_eval_info

        Train Eval Info
        """
        pass

    def test_train_eval_metrics(self) -> None:
        """Test case for train_eval_metrics

        Train Eval Metrics
        """
        pass

    def test_train_metacat(self) -> None:
        """Test case for train_metacat

        Train Metacat
        """
        pass

    def test_train_supervised(self) -> None:
        """Test case for train_supervised

        Train Supervised
        """
        pass

    def test_train_unsupervised(self) -> None:
        """Test case for train_unsupervised

        Train Unsupervised
        """
        pass

    def test_train_unsupervised_with_hf_dataset(self) -> None:
        """Test case for train_unsupervised_with_hf_dataset

        Train Unsupervised With Hf Dataset
        """
        pass


if __name__ == '__main__':
    unittest.main()
