
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-10-08T15:13:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f435205e41c1fd7dcba4c7e97680159c555de965",
 "version": "1.4.38"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
