from enum import Enum

class _EApiStatus(Enum):
    
    SUCCESS = 0
    NOT_INITIALIZED = 0xFFFFFFFF
    INITIALIZED = 0xFFFFFFFE
    ALLOC_ERROR = 0xFFFFFFFD
    DRIVER_TIMEOUT = 0xFFFFFFFC
    INVALID_PARAMETER = 0xFFFFFEFF
    INVALID_BLOCK_ALIGNMENT = 0xFFFFFEFE
    INVALID_BLOCK_LENGTH = 0xFFFFFEFD
    INVALID_DIRECTION = 0xFFFFFEFC
    INVALID_BITMASK = 0xFFFFFEFB
    RUNNING = 0xFFFFFEFA
    UNSUPPORTED = 0xFFFFFCFF
    NOT_FOUND = 0xFFFFFBFF
    TIMEOUT = 0xFFFFFBFE
    BUSY_COLLISION = 0xFFFFFBFD
    READ_ERROR = 0xFFFFFAFF
    WRITE_ERROR = 0xFFFFFAFE
    MORE_DATA = 0xFFFFF9FF
    LOCKED = 0xFFFFF8FF
    GET_STATUS_ERROR = 0xFFFFF8FE
    READ_ONLY = 0xFFFFF8FD
    PIN_UNAVAILABLE = 0xFFFFF7FD
    SHARE_VIOLATION = 0xFFFFF6FD
    MUXING_CONFLICT = 0xFFFFF5FD
    NOT_PINOPEN = 0xFFFFF4FD
    ERROR = 0xFFFFF0FF