from enum import Enum

class _SusiIotStatus(Enum):
    
    SUCCESS = 0x00000000
    NOT_INITIALIZED = 0xFFFFFFFF    
    INITIALIZED = 0xFFFFFFFE    
    ALLOC_ERROR = 0xFFFFFFFD    
    DRIVER_TIMEOUT = 0xFFFFFFFC    
    INVALID_PARAMETER = 0xFFFFFEFF    
    INVALID_BLOCK_ALIGNMENT = 0xFFFFFEFE    
    INVALID_BLOCK_LENGTH = 0xFFFFFEFD    
    INVALID_DIRECTION = 0xFFFFFEFC    
    INVALID_BITMASK = 0xFFFFFEFB    
    RUNNING = 0xFFFFFEFA    
    UNSUPPORTED = 0xFFFFFCFF    
    NOT_FOUND = 0xFFFFFBFF    
    TIMEOUT = 0xFFFFFBFE    
    BUSY_COLLISION = 0xFFFFFBFD    
    READ_ERROR = 0xFFFFFAFF    
    WRITE_ERROR = 0xFFFFFAFE    
    MORE_DATA = 0xFFFFF9FF    
    ERROR = 0xFFFFF0FF    
    JSON_TYPE_ERROR = 0xFFFFF8FF    
    JSON_OBJECT_EMPTY = 0xFFFFF8FE