
COMMANDMENTS = [
    {"id":1,"key":"speed","title":"Speed is everything","definition":"CDS must feel instantaneous at the point of decision; keep perceived UI latency under a second and typical backend responses near or below 300 ms to avoid cognitive tax.","weight":1.1,"hint":"Reduce end-to-end latency, preload data, avoid blocking calls."},
    {"id":2,"key":"anticipate_realtime","title":"Anticipate needs and deliver in real time","definition":"Surface the right insight exactly when a clinician is about to act by triggering on meaningful events such as order entry, abnormal labs, deteriorating vitals, or fresh diagnoses.","weight":1.0,"hint":"Map event triggers to decision points; prefer event-driven over batch."},
    {"id":3,"key":"fit_workflow","title":"Fit into the user’s workflow","definition":"Embed guidance natively in EHR steps; keep users in context with inline cards, context-aware suggestions, and single-click actions without window hopping.","weight":1.0,"hint":"Render inline at the decision locus; minimize navigation and mode switching."},
    {"id":4,"key":"micro_ux","title":"Little things can make a big difference","definition":"Micro-optimizations compound: clear microcopy, sensible defaults, pre-populated fields, clinically ordered controls, and accessible layouts reduce friction and error.","weight":0.8,"hint":"Tight copy, smart defaults, focus order, and accessibility."},
    {"id":5,"key":"resist_stopping","title":"Recognize that clinicians resist stopping","definition":"Hard stops invite unsafe workarounds; reserve for high-hazard scenarios with strong evidence and safer alternatives. Prefer constrained choice and salient warnings.","weight":0.9,"hint":"Tier severity; hard stops only for high risk with alternatives."},
    {"id":6,"key":"redirect_not_block","title":"Changing direction is easier than stopping","definition":"When a choice is suboptimal, guide toward a safer path without halting progress using side-by-side safer options, curated order sets, and one-click corrections.","weight":0.9,"hint":"Offer immediate low-friction alternatives over prohibition."},
    {"id":7,"key":"simplicity","title":"Simple interventions work best","definition":"Favor the smallest effective nudge. Concise rules, checklists, and pre-configured orders often outperform sprawling logic; remove nonessential steps.","weight":0.9,"hint":"Minimal viable guidance that still moves outcomes."},
    {"id":8,"key":"ask_only_when_needed","title":"Ask for additional information only when you really need it","definition":"Minimize manual entry. Auto-populate from the chart and request new inputs only when they materially change the recommendation or risk estimate.","weight":1.0,"hint":"Pre-fill ≥80% fields; ≤2 new inputs for routine nudges."},
    {"id":9,"key":"monitor_feedback","title":"Monitor impact, get feedback, and respond","definition":"Instrument CDS like a living system. Track firing rate, acceptance, overrides and reasons, false positives, time-to-action, and outcomes; review with clinicians and iterate.","weight":1.0,"hint":"Dashboards, regular reviews, and rapid adaptation."},
    {"id":10,"key":"manage_knowledge","title":"Manage and maintain your knowledge-based systems","definition":"Treat CDS knowledge as governed content with provenance, versioning, change control, ownership, review cadence, evidence links, scope, contraindications, privacy and security posture.","weight":1.1,"hint":"Assign owners, cite sources, version changes, retire stale artifacts."}
]
TITLE_BY_KEY = {c["key"]: c["title"] for c in COMMANDMENTS}
DEFINITION_BY_KEY = {c["key"]: c["definition"] for c in COMMANDMENTS}
