
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-10-08T12:39:38+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "99a08f2d85a1b5dae38a09c080f5d00184e67155",
 "version": "1.26.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
