#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2506-12-gdb1f2a30"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2506
#define NETGEN_VERSION_TWEAK 12
#define NETGEN_VERSION_HASH "gdb1f2a30"
#endif // NETGEN_VERSION_HPP_INCLUDED
