# Generated by Django 5.2.6 on 2025-10-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_diagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagram',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='diagramassociation',
            options={'ordering': ('-created',)},
        ),
    ]
