SELECT
  -- RELADRESSE
  RELADRESSE.ADRESSENR as "S_Adresse.Adressnr",
  RELADRESSE.ACADRESSENR,
  RELADRESSE.ANSCHRIFTNR,
  RELADRESSE.FIRMANR,
  RELADRESSE.PERSONNR,
  RELADRESSE.CREATEDATE,
  RELADRESSE.ACRMANSCHRIFTNR,
  RELADRESSE.ACRMEXPORTDATE,
  RELADRESSE.ACRMFIRMANR,
  RELADRESSE.ACRMPERSONNR,

  -- RELANSCH
  an.ANSCHRIFTNR           AS RELANSCH_ANSCHRIFTNR,
  an.ADDRESS1            AS "S_Kunde.Anschrift1",
  an.BEMERKUNG,
  an.HIGHWAY,
  an.ILN,
  an.LAND,
  an.LANDKNG,
  an.NAME1,
  an.NAME2,
  an.NAME3,
  an.ORT,
  an.PLZORT,
  an.PLZPOSTFACH,
  an.POSTFACH,
  an.POSTRESTANTE,
  an.RURALROUTE,
  an.SPRACHKNZ,
  an.STAAT,
  an.STRASSE,
  an.SUBTYPE0,
  an.THIRDPARTY,
  an.VERWENDUNG1,
  an.WERK,
  an.ATO0147ADDTAXNUMBER,
  an.USGESPERRT,
  an.USSPERRGRUND,

  -- RELFIRMA
  fi.FIRMANR               AS "S_Kunde.Kunde",
  fi.ABCKLAS,
  fi.BANK,
  fi.BANKCOUNTRYCODE,
  fi.BEMERKUNG,
  fi.BIC,
  fi.BLZ,
  fi.EAN,
  fi.EPOS,
  fi.FGKNZ_1,
  fi.FGKNZ_2,
  fi.FGKNZ_3,
  fi.FGKNZ_4,
  fi.FGKNZ_5,
  fi.FREMDNR,
  fi.GFORM,
  fi.IBAN,
  fi.KTO,
  fi.KTXT,
  fi.LIEFERMODELL,
--   fi.LOCKED,
--   fi.LOCKREASON,
--   fi.MANDATE,
  fi.MITARBEITER,
  fi.NAME,
  fi.SACHBEARBEITER,
  fi.SACHBEREICH,
  fi.SPRACHKNZ,
  fi.STANDARDLIEFERZEIT,
  fi.STATUS1,
  fi.STATUS3,
  fi.STATUS4,
  fi.SUCHBEGRIFF,
  fi.TAXNO,
  fi.TEXTNR,
  fi.USTIDNR,
  fi.VERWENDUNG1,
  fi.VERWENDUNG12,
  fi.VERWENDUNG13,
  fi.VERWENDUNG14,
  fi.VERWENDUNG15,
  fi.VERWENDUNG16,
  fi.VERWENDUNG2,
  fi.VERWENDUNG3,
  fi.VERWENDUNG5,
  fi.VERWENDUNG6,
  fi.VERWENDUNG7,
  fi.CREATEDATE            AS RELFIRMA_CREATEDATE,
  fi.USGESPERRT            AS RELFIRMA_USGESPERRT,
  fi.USSPERRGRUND          AS RELFIRMA_USSPERRGRUND,

  -- RELKOMM
--   ko.Kennung               AS RELKOMM_Kennung,
  ko.ADRESSENR             AS RELKOMM_ADRESSENR,
  ko.KOMART,
  ko.NUMMER,
  ko.BEMERKUNG             AS RELKOMM_BEMERKUNG,

  -- RELACP
--   acp.Kennung              AS RELACP_Kennung,
  acp.MNR                  AS RELACP_MNR,
  acp.RAEXT,
  acp.RAINT,
  acp.RVERWEND_1,
  acp.RVERWEND_2,
  acp.RVERWEND_3,
  acp.RVERWEND_4,
  acp.BELEGDAT15,
  acp.VERTRETER1,
  acp.VERTRETER2,
  acp.VERTRGRP1,
  acp.VERTRGRP2,
  acp.INLKTO,
  acp.EUKTO,
  acp.AUSLKTO,
  acp.ADRNR0,
  acp.ADRNR1,
  acp.ADRNR2,
  acp.ADRNR3,
  acp.ADRNR4,
  acp.ADRNR5,
  acp.ADRNR6,
  acp.ADRNR7,
  acp.ADRNR8,
  acp.ADRNR9,
  acp.ADRNR10,
  acp.ADRNR11,
  acp.ADRNR12,
  acp.ADRNR13,
  acp.ADRNR14,
  acp.ADRNR15,
--   acp.ADRNRGOODSRETURN,
--   acp.FORMNRGOODSRETURNACCEPT,
--   acp.FORMNRGOODSRETURNREJECT,
  acp.SOKNZTEILLIEF,
  acp.SOKNZSAMRECH,
  acp.SOKNZSAMLIEF,
  acp.SOKNZLIEFSPERR,
  acp.SOKNZTZFIRMA,
  acp.TEXT0,
  acp.TEXT1,
  acp.TEXT3,
  acp.TEXT4,
  acp.ZBED,
  acp.WE,
  acp.WARENNR,
  acp.PREISKNZ,
  acp.RABKNZBR1,
  acp.RABKNZBR2,
  acp.RABKNZHR1,
  acp.RABAR,
  acp.MWSTKNZ,
  acp.PROVKNZ1,
  acp.PROVKNZ2,
  acp.URSPINLAND,
  acp.URSPAUSLAND,
  acp.FORMNR0ANZ,
  acp.FORMNR1ANZ,
  acp.FORMNR2ANZ,
  acp.FORMNR3ANZ,
  acp.FORMNR4ANZ,
--   acp.FORMNRGOODSRETURNACCEPTANZ,
--   acp.FORMNRGOODSRETURNREJECTANZ,
  acp.ADDRPERSACC,
  acp.DISTACTIVE,
  acp.DEBITNOTEADDRESSNO,
  acp.DEBITNOTECOPIES,
  acp.DEBITNOTECANCELCOPIES,
  acp.DELIVERYADVICEADDRESSNO,
  acp.DELIVERYADVICECOPIES,
--   acp.CONFREMINDERADDRESSNO,
--   acp.CONFREMINDERPRINTCOPYS,
--   acp.COSTESTIMATIONADDRESSNO,
--   acp.COSTESTIMATIONPRINTCOPYS,
  acp.NOSQLFLD1,
  acp.MINLIEFWERT,
  acp.RABKNZMR,
  acp.RABKNZWR,
  acp.USLIEFERPRIO,
  acp.USPROVSATZV1,
  acp.USPROVSATZV2,
  acp.USPROVSATZV3,
  acp.USPROVSATZV4,
  acp.USRABPROZWG,
  acp.USRABWERTWG,
  acp.USRVNO,
  acp.USRVTYP,
  acp.USSIBAWARENGRUPPE,
  acp.USSPERREAUTOKOMMI,
  acp.USTMPFIXRAB,
  acp.USVERTRETER3,
  acp.USVERTRETER4,
  acp.VALUTATAGE,

  -- RELZTLT (Länderschlüssel)
--   zt.Kennung               AS RELZTLT_Kennung,
  zt.AC_LAND,
  zt.DEFAULTLANGUAGE,
  zt.HIERARCHYLEVEL,
  zt.INTRACODELAND,
--   zt.INTRACODENUMERIC,
  zt.ISOCODELAND,
  zt.KTXT,
  zt.LANDTYP,
  zt.RPMODIFICATION,
  zt.SPRACHE,
  zt.STATKNG,
  zt.ZTKEY,
  zt.TABNAME,

--   -- BLND_BSTA (Bundesland/Staat)
--   bl."Bundesland /Staat"                AS BLND_Bundesland_Staat,
--   bl."Bezeichnung Bundesland/Staat"     AS BLND_Bezeichnung_Bundesland_Staat,
--   bl."RELANSCH.LAND"                    AS BLND_RELANSCH_LAND,
--   bl.CBL,
--   bl.Staat,
--   bl.BLFA,
--   bl.ELPR,
--   bl.SBLa,

--   -- Regions
--   reg.Kennung                            AS Regions_Kennung,
--   reg."Region.S_Region.Region"           AS Region,
--   reg."Region.ISO-Code für die Region"   AS Region_ISO_Code,
--   reg."Region.S_RegionSpr.Bezeichnung"   AS Region_Bezeichnung,
--   reg."Region.Land"                      AS Region_Land,

--   MP_S_Kunde.Kunde (001)
--   sk."S_Kunde.Kunde"               AS S_Kunde_Kunde_001,
--   sk.FIRMANR                              AS SK_FIRMANR,

  -- MP_CRM_Kunde (zwei unterschiedliche Joins)
--   crm_sel."MP.KDNR_SELECTED"             AS KDNR_SELECTED,
--   crm_sel."MP.KDNR_DISABLED"             AS KDNR_DISABLED_when_selected,
--   crm_dis."MP.KDNR_SELECTED"             AS KDNR_SELECTED_when_disabled,
--   crm_dis."MP.KDNR_DISABLED"             AS KDNR_DISABLED
FROM RELADRESSE 
LEFT JOIN RELANSCH AS an
  ON RELADRESSE.ANSCHRIFTNR = an.ANSCHRIFTNR
LEFT JOIN RELFIRMA AS fi
  ON RELADRESSE.FIRMANR = fi.FIRMANR
LEFT JOIN RELKOMM AS ko
  ON RELADRESSE.ADRESSENR = ko.ADRESSENR
LEFT JOIN RELACP AS acp
  ON RELADRESSE.FIRMANR = acp.MNR
LEFT JOIN RELZTLT AS zt
  ON an.LANDKNG = zt.ZTKEY
-- LEFT JOIN BLND_BSTA AS bl
--   ON an.LAND = bl."RELANSCH.LAND"
-- LEFT JOIN Regions AS reg
--   ON zt.INTRACODELAND = reg."Region.ISO-Code für die Region"
-- LEFT JOIN "MP_S_Kunde.Kunde (001)" AS sk
--   ON fi.FIRMANR = sk.FIRMANR
-- LEFT JOIN MP_CRM_Kunde AS crm_sel
--   ON fi.FIRMANR = crm_sel."MP.KDNR_SELECTED"
-- LEFT JOIN MP_CRM_Kunde AS crm_dis
--   ON fi.FIRMANR = crm_dis."MP.KDNR_DISABLED";
LIMIT 100