"""Code generated by fastpix (https://fastpix.io). DO NOT EDIT."""

from __future__ import annotations
from .basicaccesspolicy import BasicAccessPolicy
from ..types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PlaybackSettingsTypedDict(TypedDict):
    r"""Displays the result of the playback settings."""

    access_policy: NotRequired[BasicAccessPolicy]
    r"""Basic access policy for media content"""


class PlaybackSettings(BaseModel):
    r"""Displays the result of the playback settings."""

    access_policy: Annotated[
        Optional[BasicAccessPolicy], pydantic.Field(alias="accessPolicy")
    ] = None
    r"""Basic access policy for media content"""
