"""Type hints for aiochainscan_fastabi Rust module."""

from typing import Any

def decode_input(input_data: bytes, abi_json: str) -> str: ...
def decode_one(calldata: bytes, abi_json: str) -> dict[str, Any]: ...
def decode_many(calldatas: list[bytes], abi_json: str) -> list[dict[str, Any]]: ...
def decode_many_direct(calldatas: list[bytes], abi: Any) -> list[dict[str, Any]]: ...
def decode_many_raw(
    calldatas: list[bytes], abi_json: str
) -> list[tuple[str, tuple[Any, ...]]]: ...
def decode_many_hex(hex_inputs: list[str], abi_json: str) -> list[dict[str, Any]]: ...
def decode_one_direct(calldata: bytes, abi: Any) -> dict[str, Any]: ...
def decode_many_flat(calldatas: list[bytes], abi_json: str) -> list[list[Any]]: ...
