__all__ = (
    "PyKAdminException",
    "KAdminException",
    "KerberosException",
    "EncryptionTypeConversion",
    "SaltTypeConversion",
    "NullPointerDereference",
    "CStringConversion",
    "CStringImportFromVec",
    "StringConversion",
    "ThreadSendError",
    "ThreadRecvError",
    "TimestampConversion",
    "DateTimeConversion",
    "DurationConversion",
)

class PyKAdminException(Exception): ...

class KAdminException(PyKAdminException):
    code: int
    origin_message: str

class KerberosException(PyKAdminException):
    code: int
    origin_message: str

class EncryptionTypeConversion(PyKAdminException): ...
class SaltTypeConversion(PyKAdminException): ...
class NullPointerDereference(PyKAdminException): ...
class CStringConversion(PyKAdminException): ...
class CStringImportFromVec(PyKAdminException): ...
class StringConversion(PyKAdminException): ...
class ThreadSendError(PyKAdminException): ...
class ThreadRecvError(PyKAdminException): ...
class TimestampConversion(PyKAdminException): ...
class DateTimeConversion(PyKAdminException): ...
class DurationConversion(PyKAdminException): ...
