# Authentication
ENV_API_KEY = "ARIZE_API_KEY"

# Server configuration env vars
ENV_API_HOST = "ARIZE_API_HOST"
ENV_API_INSECURE = "ARIZE_API_INSECURE"
ENV_FLIGHT_HOST = "ARIZE_FLIGHT_HOST"
ENV_FLIGHT_PORT = "ARIZE_FLIGHT_PORT"
ENV_FLIGHT_TRANSPORT_SCHEME = "ARIZE_FLIGHT_TRANSPORT_SCHEME"
ENV_REQUEST_VERIFY = "ARIZE_REQUEST_VERIFY"

# Server configuration default values
DEFAULT_API_HOST = "api.arize.com"  # NOTE: Must not prefix with https://
DEFAULT_API_INSECURE = False
DEFAULT_FLIGHT_HOST = "flight.arize.com"  # NOTE: Must not prefix with https://
DEFAULT_FLIGHT_PORT = 443
DEFAULT_FLIGHT_TRANSPORT_SCHEME = "grpc+tls"
DEFAULT_REQUEST_VERIFY = True

# ML Streaming configuration
ENV_STREAM_MAX_WORKERS = "ARIZE_STREAM_MAX_WORKERS"
ENV_STREAM_MAX_QUEUE_BOUND = "ARIZE_STREAM_MAX_QUEUE_BOUND"
DEFAULT_STREAM_MAX_WORKERS = 8
DEFAULT_STREAM_MAX_QUEUE_BOUND = 5000

# Logging
ENV_LOG_ENABLE = "ARIZE_LOG_ENABLE"
ENV_LOG_LEVEL = "ARIZE_LOG_LEVEL"
ENV_LOG_STRUCTURED = "ARIZE_LOG_STRUCTURED"
DEFAULT_LOG_ENABLE = True
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_STRUCTURED = False
