
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-10-07T17:23:59+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "05e81d137ba24c9d2af0bab20464f45c03ef374d",
 "version": "2025.10.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
