

from onescience.flax_models.alphafold3.cpp import cif_dict

class MmcifLayout:
  def atom_range(self, residue_index: int) -> tuple[int, int]: ...
  def chain_starts(self) -> list[int]: ...
  def chains(self) -> list[int]: ...
  def model_offset(self) -> int: ...
  def num_atoms(self) -> int: ...
  def num_chains(self) -> int: ...
  def num_models(self) -> int: ...
  def num_residues(self) -> int: ...
  def residue_range(self, chain_index: int) -> tuple[int, int]: ...
  def residue_starts(self) -> list[int]: ...
  def residues(self) -> list[int]: ...

def from_mmcif(mmcif: cif_dict.CifDict, model_id: str = ...) -> MmcifLayout: ...
