# Generated by Django 5.0.4 on 2024-04-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flex_report", "0012_tablebuttoncolor_alter_tablebutton_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="column_type",
            field=models.CharField(
                choices=[("dynamic", "Dynamic"), ("model", "Model")],
                default="model",
                max_length=10,
                verbose_name="Column Type",
            ),
        ),
    ]
