"""A logging formatter for colored output."""

from intelliw.utils.colorlog.formatter import (
    ColoredFormatter,
    LevelFormatter,
    TTYColoredFormatter,
    default_log_colors,
)
from intelliw.utils.colorlog.wrappers import (
    CRITICAL,
    DEBUG,
    ERROR,
    FATAL,
    INFO,
    NOTSET,
    StreamHandler,
    WARN,
    WARNING,
    basicConfig,
    critical,
    debug,
    error,
    exception,
    getLogger,
    info,
    log,
    root,
    warning,
)

__all__ = (
    "CRITICAL",
    "DEBUG",
    "ERROR",
    "FATAL",
    "INFO",
    "NOTSET",
    "WARN",
    "WARNING",
    "ColoredFormatter",
    "LevelFormatter",
    "StreamHandler",
    "TTYColoredFormatter",
    "basicConfig",
    "critical",
    "debug",
    "default_log_colors",
    "error",
    "exception",
    "exception",
    "getLogger",
    "info",
    "log",
    "root",
    "warning",
)
