# -*- coding: utf-8 -*-
from setuptools import setup

setup(
    name='amazon_ad_sdk',
    version='0.2.19',
    packages=['amazon_ad',
              'amazon_ad.api',
              'amazon_ad.api.sb',
              'amazon_ad.api.sp',
              'amazon_ad.api.sd',
              'amazon_ad.api.dsp',
              'amazon_ad.api.amazon_attribution',
              'amazon_ad.client',
              'amazon_ad.core',
              'amazon_ad.core.utils',
              'amazon_ad.api_v3',
              'amazon_ad.api_v3.sp',
              'amazon_ad.api_v3.sb',
              'amazon_ad.api_v3.sd',
              'amazon_ad.api_v3.billing',
              ],
    url='',
    license='',
    author='Ryan',
    author_email='931798845@qq.com',
    description='Amazon Advertising SDK',
    setup_requires=['wheel'],
    install_requires=[
        "arrow==0.12.1",
        "certifi==2018.10.15",
        "chardet==3.0.4",
        "idna==2.7",
        "ipython==7.34.0",
        "python-dateutil==2.7.5",
        "requests==2.28.1",
        "six==1.11.0",
        "urllib3==1.26.1",
        "wcwidth==0.1.9",
    ],
    python_requires='>=3.6',
)
