#+startup: overview
#+options: num:nil ^:nil toc:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,11pt,twoside]
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage[textwidth=18cm, textheight=22.5cm]{geometry}
#+latex_header: \usepackage{ifthen,changepage}
#+exclude_tags: solution noexport
\pagestyle{empty}

\thispagestyle{empty}

* Examen
- N: 1
* Another question

   This question is easier than you think. Please provide a solution !!

   

* Question with png

   Another nice figure

   #+attr_latex: :float :width .3\textwidth
   file:triangle.png

   

* Question with open answer

   This is an open question, respond with a long answer
   

** 

\cleardoublepage

* Examen
- N: 2
* Question

   This is the first question, can you answer ?

   

* Question with png

   Another nice figure

   #+attr_latex: :float :width .3\textwidth
   file:triangle.png

   

* Question with open answer

   This is an open question, respond with a long answer
   

** 

\cleardoublepage

* Examen
- N: 3
* Question with figure


   A question may include a figure

   #+attr_latex: :float :width .4\textwidth 
   file:cc.jpeg



* Question with png

   Another nice figure

   #+attr_latex: :float :width .3\textwidth
   file:triangle.png

   

* Question with open answer

   This is an open question, respond with a long answer
   

** 

\cleardoublepage

* Examen
- N: 4
* Another question

   This question is easier than you think. Please provide a solution !!

   

* Question with items

   Which one of the following is correct ?

   1. First answer 
   2. Second answer
   3. Third answer
   4. Fourth answer

   

* Exercice

   Please compute the hypothenuse of a triangle with sides 3 and 4.

   

** 

\cleardoublepage

* Examen
- N: 5
* Question with figure


   A question may include a figure

   #+attr_latex: :float :width .4\textwidth 
   file:cc.jpeg



* Question with items

   Which one of the following is correct ?

   1. First answer 
   2. Second answer
   3. Third answer
   4. Fourth answer

   

* Exercice

   Please compute the hypothenuse of a triangle with sides 3 and 4.

   

** 

\cleardoublepage

* Examen
- N: 6
* Question with figure


   A question may include a figure

   #+attr_latex: :float :width .4\textwidth 
   file:cc.jpeg



* Question with items

   Which one of the following is correct ?

   1. First answer 
   2. Second answer
   3. Third answer
   4. Fourth answer

   

* Exercice

   Please compute the hypothenuse of a triangle with sides 3 and 4.

   

** 

\cleardoublepage

* Examen
- N: 7
* Another question

   This question is easier than you think. Please provide a solution !!

   

* Question with png

   Another nice figure

   #+attr_latex: :float :width .3\textwidth
   file:triangle.png

   

* Question with open answer

   This is an open question, respond with a long answer
   

** 

\cleardoublepage

* Examen
- N: 8
* Another question

   This question is easier than you think. Please provide a solution !!

   

* Question with items

   Which one of the following is correct ?

   1. First answer 
   2. Second answer
   3. Third answer
   4. Fourth answer

   

* Exercice

   Please compute the hypothenuse of a triangle with sides 3 and 4.

   

** 

\cleardoublepage

* Examen
- N: 9
* Question with figure


   A question may include a figure

   #+attr_latex: :float :width .4\textwidth 
   file:cc.jpeg



* Question with png

   Another nice figure

   #+attr_latex: :float :width .3\textwidth
   file:triangle.png

   

* Question with open answer

   This is an open question, respond with a long answer
   

** 

\cleardoublepage

* Examen
- N: 10
* Question

   This is the first question, can you answer ?

   

* Question with png

   Another nice figure

   #+attr_latex: :float :width .3\textwidth
   file:triangle.png

   

* Question with open answer

   This is an open question, respond with a long answer
   

** 

\cleardoublepage

* Examen
- N: 11
* Question with figure


   A question may include a figure

   #+attr_latex: :float :width .4\textwidth 
   file:cc.jpeg



* Question with items

   Which one of the following is correct ?

   1. First answer 
   2. Second answer
   3. Third answer
   4. Fourth answer

   

* Exercice

   Please compute the hypothenuse of a triangle with sides 3 and 4.

   

** 

\cleardoublepage

* Examen
- N: 12
* Question with figure


   A question may include a figure

   #+attr_latex: :float :width .4\textwidth 
   file:cc.jpeg



* Question with png

   Another nice figure

   #+attr_latex: :float :width .3\textwidth
   file:triangle.png

   

* Question with open answer

   This is an open question, respond with a long answer
   

** 

\cleardoublepage

* Examen
- N: 13
* Another question

   This question is easier than you think. Please provide a solution !!

   

* Question with items

   Which one of the following is correct ?

   1. First answer 
   2. Second answer
   3. Third answer
   4. Fourth answer

   

* Question with open answer

   This is an open question, respond with a long answer
   

** 

\cleardoublepage

* Examen
- N: 14
* Another question

   This question is easier than you think. Please provide a solution !!

   

* Question with items

   Which one of the following is correct ?

   1. First answer 
   2. Second answer
   3. Third answer
   4. Fourth answer

   

* Exercice

   Please compute the hypothenuse of a triangle with sides 3 and 4.

   

** 

\cleardoublepage

* Examen
- N: 15
* Another question

   This question is easier than you think. Please provide a solution !!

   

* Question with items

   Which one of the following is correct ?

   1. First answer 
   2. Second answer
   3. Third answer
   4. Fourth answer

   

* Exercice

   Please compute the hypothenuse of a triangle with sides 3 and 4.

   

** 

\cleardoublepage

* Examen
- N: 16
* Question with figure


   A question may include a figure

   #+attr_latex: :float :width .4\textwidth 
   file:cc.jpeg



* Question with items

   Which one of the following is correct ?

   1. First answer 
   2. Second answer
   3. Third answer
   4. Fourth answer

   

* Exercice

   Please compute the hypothenuse of a triangle with sides 3 and 4.

   

** 

\cleardoublepage

* Examen
- N: 17
* Question with figure


   A question may include a figure

   #+attr_latex: :float :width .4\textwidth 
   file:cc.jpeg



* Question with items

   Which one of the following is correct ?

   1. First answer 
   2. Second answer
   3. Third answer
   4. Fourth answer

   

* Exercice

   Please compute the hypothenuse of a triangle with sides 3 and 4.

   

** 

\cleardoublepage

* Examen
- N: 18
* Another question

   This question is easier than you think. Please provide a solution !!

   

* Question with png

   Another nice figure

   #+attr_latex: :float :width .3\textwidth
   file:triangle.png

   

* Question with open answer

   This is an open question, respond with a long answer
   

** 

\cleardoublepage

* Examen
- N: 19
* Another question

   This question is easier than you think. Please provide a solution !!

   

* Question with items

   Which one of the following is correct ?

   1. First answer 
   2. Second answer
   3. Third answer
   4. Fourth answer

   

* Exercice

   Please compute the hypothenuse of a triangle with sides 3 and 4.

   

** 

\cleardoublepage

* Examen
- N: 20
* Question with figure


   A question may include a figure

   #+attr_latex: :float :width .4\textwidth 
   file:cc.jpeg



* Question with png

   Another nice figure

   #+attr_latex: :float :width .3\textwidth
   file:triangle.png

   

* Question with open answer

   This is an open question, respond with a long answer
   

** 

\cleardoublepage

* Examen
- N: 21
* Another question

   This question is easier than you think. Please provide a solution !!

   

* Question with items

   Which one of the following is correct ?

   1. First answer 
   2. Second answer
   3. Third answer
   4. Fourth answer

   

* Question with open answer

   This is an open question, respond with a long answer
   

** 

\cleardoublepage

* Examen
- N: 22
* Question

   This is the first question, can you answer ?

   

* Question with items

   Which one of the following is correct ?

   1. First answer 
   2. Second answer
   3. Third answer
   4. Fourth answer

   

* Exercice

   Please compute the hypothenuse of a triangle with sides 3 and 4.

   

** 

\cleardoublepage

* Examen
- N: 23
* Question

   This is the first question, can you answer ?

   

* Question with items

   Which one of the following is correct ?

   1. First answer 
   2. Second answer
   3. Third answer
   4. Fourth answer

   

* Exercice

   Please compute the hypothenuse of a triangle with sides 3 and 4.

   

** 

\cleardoublepage

* Examen
- N: 24
* Question

   This is the first question, can you answer ?

   

* Question with png

   Another nice figure

   #+attr_latex: :float :width .3\textwidth
   file:triangle.png

   

* Question with open answer

   This is an open question, respond with a long answer
   

** 

\cleardoublepage

* Examen
- N: 25
* Question with figure


   A question may include a figure

   #+attr_latex: :float :width .4\textwidth 
   file:cc.jpeg



* Question with png

   Another nice figure

   #+attr_latex: :float :width .3\textwidth
   file:triangle.png

   

* Question with open answer

   This is an open question, respond with a long answer
   

** 

\cleardoublepage

* Examen
- N: 26
* Another question

   This question is easier than you think. Please provide a solution !!

   

* Question with items

   Which one of the following is correct ?

   1. First answer 
   2. Second answer
   3. Third answer
   4. Fourth answer

   

* Exercice

   Please compute the hypothenuse of a triangle with sides 3 and 4.

   

** 

\cleardoublepage

* Examen
- N: 27
* Another question

   This question is easier than you think. Please provide a solution !!

   

* Question with items

   Which one of the following is correct ?

   1. First answer 
   2. Second answer
   3. Third answer
   4. Fourth answer

   

* Question with open answer

   This is an open question, respond with a long answer
   

** 

\cleardoublepage

* Examen
- N: 28
* Another question

   This question is easier than you think. Please provide a solution !!

   

* Question with items

   Which one of the following is correct ?

   1. First answer 
   2. Second answer
   3. Third answer
   4. Fourth answer

   

* Question with open answer

   This is an open question, respond with a long answer
   

** 

\cleardoublepage

* Examen
- N: 29
* Question

   This is the first question, can you answer ?

   

* Question with png

   Another nice figure

   #+attr_latex: :float :width .3\textwidth
   file:triangle.png

   

* Question with open answer

   This is an open question, respond with a long answer
   

** 

\cleardoublepage

* Examen
- N: 30
* Question with figure


   A question may include a figure

   #+attr_latex: :float :width .4\textwidth 
   file:cc.jpeg



* Question with items

   Which one of the following is correct ?

   1. First answer 
   2. Second answer
   3. Third answer
   4. Fourth answer

   

* Question with open answer

   This is an open question, respond with a long answer
   

** 

\cleardoublepage

