from collections.abc import Iterable

def unescape(v: str) -> str: ...
def parse_addresses(s: str) -> Iterable[tuple[str, dict[str, str]]]: ...

SUPPORTED_TRANSPORTS: tuple[str]

def get_connectable_addresses(addr: str) -> Iterable[str]: ...
def find_session_bus() -> str: ...
def find_system_bus() -> str: ...
def get_bus(addr: str) -> str: ...
