"""Code generated by fastpix (https://fastpix.io). DO NOT EDIT."""

from __future__ import annotations
from ..types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class NamedEntitiesResponseTypedDict(TypedDict):
    media_id: NotRequired[str]
    is_generated_named_entities: NotRequired[bool]


class NamedEntitiesResponse(BaseModel):
    media_id: Annotated[Optional[str], pydantic.Field(alias="mediaId")] = None

    is_generated_named_entities: Annotated[
        Optional[bool], pydantic.Field(alias="isGeneratedNamedEntities")
    ] = None
