"""Code generated by fastpix (https://fastpix.io). DO NOT EDIT."""

from typing import Any, Dict, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class ValidationErrorResponseData(TypedDict):
    """Validation error response data structure."""
    message: str
    errors: NotRequired[Optional[List[Dict[str, Any]]]]


class ValidationErrorResponse(Exception):
    """Validation error response exception."""
    
    def __init__(self, response_data: ValidationErrorResponseData, http_res):
        self.response_data = response_data
        self.http_res = http_res
        super().__init__(f"Validation error: {response_data.get('message', 'Unknown validation error')}")
