# coding: utf-8

"""
    Street Manager API

    See API specification Resource Guide > Work API for more information on endpoints NOTE: Swagger Editor/UI does not display all description text for enumerations and child elements, check swagger.json for full description text  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.duration_challenge_non_acceptance_response_status_response import DurationChallengeNonAcceptanceResponseStatusResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestDurationChallengeNonAcceptanceResponseStatusResponse(unittest.TestCase):
    """DurationChallengeNonAcceptanceResponseStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDurationChallengeNonAcceptanceResponseStatusResponse(self):
        """Test DurationChallengeNonAcceptanceResponseStatusResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.duration_challenge_non_acceptance_response_status_response.DurationChallengeNonAcceptanceResponseStatusResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
