ENTITY_RESPONSE = {
    "id": 6,
    "name": "XXXXXXXX - DESENTUPIDORA LTDA - EPP",
    "entities_id": 0,
    "completename": "GNEW > ",
    "comment": "",
    "level": 2,
    "sons_cache": "{\"6\":\"6\"}",
    "ancestors_cache": "[\"0\"]",
    "address": "R MARIA XDXXXXXXXXXX, 15\r\nJD OSASCO",
    "postcode": 'XXXXXXXX',
    "town": "OSASCO",
    "state": "SP",
    "country": "BRASIL",
    "website": None,
    "phonenumber": "11 XXXXXXXXXX",
    "fax": None,
    "email": None,
    "admin_email": "tatianno.alves@gnew.com.br",
    "admin_email_name": "Tatianno",
    "admin_reply": None,
    "admin_reply_name": None,
    "notification_subject_tag": None,
    "ldap_dn": None,
    "tag": None,
    "authldaps_id": 0,
    "mail_domain": None,
    "entity_ldapfilter": None,
    "mailing_signature": None,
    "cartridges_alert_repeat": -2,
    "consumables_alert_repeat": -2,
    "use_licenses_alert": -2,
    "send_licenses_alert_before_delay": -2,
    "use_certificates_alert": -2,
    "send_certificates_alert_before_delay": -2,
    "use_contracts_alert": -2,
    "send_contracts_alert_before_delay": -2,
    "use_infocoms_alert": -2,
    "send_infocoms_alert_before_delay": -2,
    "use_reservations_alert": -2,
    "autoclose_delay": -2,
    "notclosed_delay": -2,
    "calendars_id": -2,
    "auto_assign_mode": -2,
    "tickettype": -2,
    "max_closedate": "2019-03-23 11:15:14",
    "inquest_config": -2,
    "inquest_rate": 0,
    "inquest_delay": -10,
    "inquest_URL": None,
    "autofill_warranty_date": -2,
    "autofill_use_date": -2,
    "autofill_buy_date": -2,
    "autofill_delivery_date": -2,
    "autofill_order_date": -2,
    "tickettemplates_id": -2,
    "entities_id_software": -2,
    "default_contract_alert": -2,
    "default_infocom_alert": -2,
    "default_cartridges_alarm_threshold": -2,
    "default_consumables_alarm_threshold": -2,
    "delay_send_emails": -2,
    "is_notif_enable_default": -2,
    "inquest_duration": 0,
    "date_mod": "2024-11-07 19:30:51",
    "date_creation": "2019-03-23 11:15:14",
    "autofill_decommission_date": -2,
    "links": [
        {
            "rel": "Entity",
            "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
        },
        {
            "rel": "Calendar",
            "href": "https://glpi-teste.com.br/apirest.php/Calendar/-2"
        },
        {
            "rel": "TicketTemplate",
            "href": "https://glpi-teste.com.br/apirest.php/TicketTemplate/-2"
        },
        {
            "rel": "Entity",
            "href": "https://glpi-teste.com.br/apirest.php/Entity/-2"
        },
        {
            "rel": "Document_Item",
            "href": "https://glpi-teste.com.br/apirest.php/Entity/6/Document_Item/"
        }
    ]
}

ENTITIES_RESPONSE = [
    {
        "id": 0,
        "name": "GNEW",
        "entities_id": -1,
        "completename": "GNEW",
        "comment": None,
        "level": 1,
        "sons_cache": None,
        "ancestors_cache": None,
        "address": None,
        "postcode": None,
        "town": None,
        "state": None,
        "country": None,
        "website": None,
        "phonenumber": None,
        "fax": None,
        "email": None,
        "admin_email": None,
        "admin_email_name": None,
        "admin_reply": None,
        "admin_reply_name": None,
        "notification_subject_tag": None,
        "ldap_dn": None,
        "tag": 18900874000160,
        "authldaps_id": 0,
        "mail_domain": None,
        "entity_ldapfilter": None,
        "mailing_signature": None,
        "cartridges_alert_repeat": 0,
        "consumables_alert_repeat": 0,
        "use_licenses_alert": 0,
        "send_licenses_alert_before_delay": 0,
        "use_certificates_alert": 0,
        "send_certificates_alert_before_delay": 0,
        "use_contracts_alert": 0,
        "send_contracts_alert_before_delay": 0,
        "use_infocoms_alert": 0,
        "send_infocoms_alert_before_delay": 0,
        "use_reservations_alert": 0,
        "autoclose_delay": -10,
        "notclosed_delay": 0,
        "calendars_id": 2,
        "auto_assign_mode": -10,
        "tickettype": 1,
        "max_closedate": None,
        "inquest_config": 1,
        "inquest_rate": 0,
        "inquest_delay": 0,
        "inquest_URL": None,
        "autofill_warranty_date": 0,
        "autofill_use_date": 0,
        "autofill_buy_date": 0,
        "autofill_delivery_date": 0,
        "autofill_order_date": 0,
        "tickettemplates_id": 2,
        "entities_id_software": -10,
        "default_contract_alert": 0,
        "default_infocom_alert": 0,
        "default_cartridges_alarm_threshold": 10,
        "default_consumables_alarm_threshold": 10,
        "delay_send_emails": 0,
        "is_notif_enable_default": 1,
        "inquest_duration": 0,
        "date_mod": "2024-08-19 18:08:05",
        "date_creation": None,
        "autofill_decommission_date": 0,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/-1"
            },
            {
                "rel": "Calendar",
                "href": "https://glpi-teste.com.br/apirest.php/Calendar/2"
            },
            {
                "rel": "TicketTemplate",
                "href": "https://glpi-teste.com.br/apirest.php/TicketTemplate/2"
            },
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/-10"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0/Document_Item/"
            }
        ]
    },
    {
        "id": 1,
        "name": "JHLS LANCHONETE E CHOPERIA EIRELI - ME",
        "entities_id": 0,
        "completename": "GNEW > JHLS LANCHONETE E CHOPERIA EIRELI - ME",
        "comment": "",
        "level": 2,
        "sons_cache": None,
        "ancestors_cache": "[\"0\"]",
        "address": None,
        "postcode": None,
        "town": None,
        "state": None,
        "country": None,
        "website": None,
        "phonenumber": None,
        "fax": None,
        "email": None,
        "admin_email": None,
        "admin_email_name": None,
        "admin_reply": None,
        "admin_reply_name": None,
        "notification_subject_tag": None,
        "ldap_dn": None,
        "tag": None,
        "authldaps_id": 0,
        "mail_domain": None,
        "entity_ldapfilter": None,
        "mailing_signature": None,
        "cartridges_alert_repeat": -2,
        "consumables_alert_repeat": -2,
        "use_licenses_alert": -2,
        "send_licenses_alert_before_delay": -2,
        "use_certificates_alert": -2,
        "send_certificates_alert_before_delay": -2,
        "use_contracts_alert": -2,
        "send_contracts_alert_before_delay": -2,
        "use_infocoms_alert": -2,
        "send_infocoms_alert_before_delay": -2,
        "use_reservations_alert": -2,
        "autoclose_delay": -2,
        "notclosed_delay": -2,
        "calendars_id": -2,
        "auto_assign_mode": -2,
        "tickettype": -2,
        "max_closedate": "2019-03-22 14:28:36",
        "inquest_config": -2,
        "inquest_rate": 0,
        "inquest_delay": -10,
        "inquest_URL": None,
        "autofill_warranty_date": -2,
        "autofill_use_date": -2,
        "autofill_buy_date": -2,
        "autofill_delivery_date": -2,
        "autofill_order_date": -2,
        "tickettemplates_id": -2,
        "entities_id_software": -2,
        "default_contract_alert": -2,
        "default_infocom_alert": -2,
        "default_cartridges_alarm_threshold": -2,
        "default_consumables_alarm_threshold": -2,
        "delay_send_emails": -2,
        "is_notif_enable_default": -2,
        "inquest_duration": 0,
        "date_mod": "2019-03-22 18:38:15",
        "date_creation": "2019-03-22 14:28:36",
        "autofill_decommission_date": -2,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "Calendar",
                "href": "https://glpi-teste.com.br/apirest.php/Calendar/-2"
            },
            {
                "rel": "TicketTemplate",
                "href": "https://glpi-teste.com.br/apirest.php/TicketTemplate/-2"
            },
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/-2"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/1/Document_Item/"
            }
        ]
    },
    {
        "id": 2,
        "name": "JHF TELECOM - SOLUCOES EM TELECOMUNICACOES - EIRELI",
        "entities_id": 0,
        "completename": "GNEW > JHF TELECOM - SOLUCOES EM TELECOMUNICACOES - EIRELI",
        "comment": "",
        "level": 2,
        "sons_cache": None,
        "ancestors_cache": "[\"0\"]",
        "address": None,
        "postcode": None,
        "town": None,
        "state": None,
        "country": None,
        "website": None,
        "phonenumber": None,
        "fax": None,
        "email": None,
        "admin_email": None,
        "admin_email_name": None,
        "admin_reply": None,
        "admin_reply_name": None,
        "notification_subject_tag": None,
        "ldap_dn": None,
        "tag": None,
        "authldaps_id": 0,
        "mail_domain": None,
        "entity_ldapfilter": None,
        "mailing_signature": None,
        "cartridges_alert_repeat": -2,
        "consumables_alert_repeat": -2,
        "use_licenses_alert": -2,
        "send_licenses_alert_before_delay": -2,
        "use_certificates_alert": -2,
        "send_certificates_alert_before_delay": -2,
        "use_contracts_alert": -2,
        "send_contracts_alert_before_delay": -2,
        "use_infocoms_alert": -2,
        "send_infocoms_alert_before_delay": -2,
        "use_reservations_alert": -2,
        "autoclose_delay": -2,
        "notclosed_delay": -2,
        "calendars_id": -2,
        "auto_assign_mode": -2,
        "tickettype": -2,
        "max_closedate": "2019-03-22 18:39:13",
        "inquest_config": -2,
        "inquest_rate": 0,
        "inquest_delay": -10,
        "inquest_URL": None,
        "autofill_warranty_date": -2,
        "autofill_use_date": -2,
        "autofill_buy_date": -2,
        "autofill_delivery_date": -2,
        "autofill_order_date": -2,
        "tickettemplates_id": -2,
        "entities_id_software": -2,
        "default_contract_alert": -2,
        "default_infocom_alert": -2,
        "default_cartridges_alarm_threshold": -2,
        "default_consumables_alarm_threshold": -2,
        "delay_send_emails": -2,
        "is_notif_enable_default": -2,
        "inquest_duration": 0,
        "date_mod": "2019-03-22 18:39:13",
        "date_creation": "2019-03-22 18:39:13",
        "autofill_decommission_date": -2,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "Calendar",
                "href": "https://glpi-teste.com.br/apirest.php/Calendar/-2"
            },
            {
                "rel": "TicketTemplate",
                "href": "https://glpi-teste.com.br/apirest.php/TicketTemplate/-2"
            },
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/-2"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/2/Document_Item/"
            }
        ]
    },
    {
        "id": 3,
        "name": "JEEP",
        "entities_id": 2,
        "completename": "GNEW > JHF TELECOM - SOLUCOES EM TELECOMUNICACOES - EIRELI > JEEP",
        "comment": None,
        "level": 3,
        "sons_cache": None,
        "ancestors_cache": "{\"0\":\"0\",\"2\":\"2\"}",
        "address": None,
        "postcode": None,
        "town": None,
        "state": None,
        "country": None,
        "website": None,
        "phonenumber": None,
        "fax": None,
        "email": None,
        "admin_email": None,
        "admin_email_name": None,
        "admin_reply": None,
        "admin_reply_name": None,
        "notification_subject_tag": None,
        "ldap_dn": None,
        "tag": None,
        "authldaps_id": 0,
        "mail_domain": None,
        "entity_ldapfilter": None,
        "mailing_signature": None,
        "cartridges_alert_repeat": -2,
        "consumables_alert_repeat": -2,
        "use_licenses_alert": -2,
        "send_licenses_alert_before_delay": -2,
        "use_certificates_alert": -2,
        "send_certificates_alert_before_delay": -2,
        "use_contracts_alert": -2,
        "send_contracts_alert_before_delay": -2,
        "use_infocoms_alert": -2,
        "send_infocoms_alert_before_delay": -2,
        "use_reservations_alert": -2,
        "autoclose_delay": -2,
        "notclosed_delay": -2,
        "calendars_id": -2,
        "auto_assign_mode": -2,
        "tickettype": -2,
        "max_closedate": "2019-03-22 18:48:44",
        "inquest_config": -2,
        "inquest_rate": 0,
        "inquest_delay": -10,
        "inquest_URL": None,
        "autofill_warranty_date": -2,
        "autofill_use_date": -2,
        "autofill_buy_date": -2,
        "autofill_delivery_date": -2,
        "autofill_order_date": -2,
        "tickettemplates_id": -2,
        "entities_id_software": -2,
        "default_contract_alert": -2,
        "default_infocom_alert": -2,
        "default_cartridges_alarm_threshold": -2,
        "default_consumables_alarm_threshold": -2,
        "delay_send_emails": -2,
        "is_notif_enable_default": -2,
        "inquest_duration": 0,
        "date_mod": "2019-03-22 18:48:44",
        "date_creation": "2019-03-22 18:48:44",
        "autofill_decommission_date": -2,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/2"
            },
            {
                "rel": "Calendar",
                "href": "https://glpi-teste.com.br/apirest.php/Calendar/-2"
            },
            {
                "rel": "TicketTemplate",
                "href": "https://glpi-teste.com.br/apirest.php/TicketTemplate/-2"
            },
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/-2"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/3/Document_Item/"
            }
        ]
    },
    {
        "id": 4,
        "name": "REALIZA",
        "entities_id": 2,
        "completename": "GNEW > JHF TELECOM - SOLUCOES EM TELECOMUNICACOES - EIRELI > REALIZA",
        "comment": None,
        "level": 3,
        "sons_cache": None,
        "ancestors_cache": "{\"0\":\"0\",\"2\":\"2\"}",
        "address": None,
        "postcode": None,
        "town": None,
        "state": None,
        "country": None,
        "website": None,
        "phonenumber": None,
        "fax": None,
        "email": None,
        "admin_email": None,
        "admin_email_name": None,
        "admin_reply": None,
        "admin_reply_name": None,
        "notification_subject_tag": None,
        "ldap_dn": None,
        "tag": None,
        "authldaps_id": 0,
        "mail_domain": None,
        "entity_ldapfilter": None,
        "mailing_signature": None,
        "cartridges_alert_repeat": -2,
        "consumables_alert_repeat": -2,
        "use_licenses_alert": -2,
        "send_licenses_alert_before_delay": -2,
        "use_certificates_alert": -2,
        "send_certificates_alert_before_delay": -2,
        "use_contracts_alert": -2,
        "send_contracts_alert_before_delay": -2,
        "use_infocoms_alert": -2,
        "send_infocoms_alert_before_delay": -2,
        "use_reservations_alert": -2,
        "autoclose_delay": -2,
        "notclosed_delay": -2,
        "calendars_id": -2,
        "auto_assign_mode": -2,
        "tickettype": -2,
        "max_closedate": "2019-03-22 18:48:51",
        "inquest_config": -2,
        "inquest_rate": 0,
        "inquest_delay": -10,
        "inquest_URL": None,
        "autofill_warranty_date": -2,
        "autofill_use_date": -2,
        "autofill_buy_date": -2,
        "autofill_delivery_date": -2,
        "autofill_order_date": -2,
        "tickettemplates_id": -2,
        "entities_id_software": -2,
        "default_contract_alert": -2,
        "default_infocom_alert": -2,
        "default_cartridges_alarm_threshold": -2,
        "default_consumables_alarm_threshold": -2,
        "delay_send_emails": -2,
        "is_notif_enable_default": -2,
        "inquest_duration": 0,
        "date_mod": "2019-03-22 18:48:51",
        "date_creation": "2019-03-22 18:48:51",
        "autofill_decommission_date": -2,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/2"
            },
            {
                "rel": "Calendar",
                "href": "https://glpi-teste.com.br/apirest.php/Calendar/-2"
            },
            {
                "rel": "TicketTemplate",
                "href": "https://glpi-teste.com.br/apirest.php/TicketTemplate/-2"
            },
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/-2"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/4/Document_Item/"
            }
        ]
    },
    {
        "id": 5,
        "name": "JOCKEY",
        "entities_id": 2,
        "completename": "GNEW > JHF TELECOM - SOLUCOES EM TELECOMUNICACOES - EIRELI > JOCKEY",
        "comment": "ACESSO REMOTO\r\njockey.ramaisip.com.br -p 7022\r\n200.206.42.50 -p 7022",
        "level": 3,
        "sons_cache": "{\"5\":\"5\"}",
        "ancestors_cache": "{\"0\":\"0\",\"2\":\"2\"}",
        "address": None,
        "postcode": None,
        "town": None,
        "state": None,
        "country": None,
        "website": None,
        "phonenumber": None,
        "fax": None,
        "email": None,
        "admin_email": None,
        "admin_email_name": None,
        "admin_reply": None,
        "admin_reply_name": None,
        "notification_subject_tag": None,
        "ldap_dn": None,
        "tag": None,
        "authldaps_id": 0,
        "mail_domain": None,
        "entity_ldapfilter": None,
        "mailing_signature": None,
        "cartridges_alert_repeat": -2,
        "consumables_alert_repeat": -2,
        "use_licenses_alert": -2,
        "send_licenses_alert_before_delay": -2,
        "use_certificates_alert": -2,
        "send_certificates_alert_before_delay": -2,
        "use_contracts_alert": -2,
        "send_contracts_alert_before_delay": -2,
        "use_infocoms_alert": -2,
        "send_infocoms_alert_before_delay": -2,
        "use_reservations_alert": -2,
        "autoclose_delay": -2,
        "notclosed_delay": -2,
        "calendars_id": -2,
        "auto_assign_mode": -2,
        "tickettype": -2,
        "max_closedate": "2019-03-22 18:49:08",
        "inquest_config": -2,
        "inquest_rate": 0,
        "inquest_delay": -10,
        "inquest_URL": None,
        "autofill_warranty_date": -2,
        "autofill_use_date": -2,
        "autofill_buy_date": -2,
        "autofill_delivery_date": -2,
        "autofill_order_date": -2,
        "tickettemplates_id": -2,
        "entities_id_software": -2,
        "default_contract_alert": -2,
        "default_infocom_alert": -2,
        "default_cartridges_alarm_threshold": -2,
        "default_consumables_alarm_threshold": -2,
        "delay_send_emails": -2,
        "is_notif_enable_default": -2,
        "inquest_duration": 0,
        "date_mod": "2019-10-23 11:41:51",
        "date_creation": "2019-03-22 18:49:08",
        "autofill_decommission_date": -2,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/2"
            },
            {
                "rel": "Calendar",
                "href": "https://glpi-teste.com.br/apirest.php/Calendar/-2"
            },
            {
                "rel": "TicketTemplate",
                "href": "https://glpi-teste.com.br/apirest.php/TicketTemplate/-2"
            },
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/-2"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/5/Document_Item/"
            }
        ]
    },
    {
        "id": 6,
        "name": "ALTERNATIVA - DESENTUPIDORA LTDA - EPP",
        "entities_id": 0,
        "completename": "GNEW > ",
        "comment": "",
        "level": 2,
        "sons_cache": "{\"6\":\"6\"}",
        "ancestors_cache": "[\"0\"]",
        "address": "R MARIA VACARI DE SOUZA, 15\r\nJD OSASCO",
        "postcode": 6170120,
        "town": "OSASCO",
        "state": "SP",
        "country": "BRASIL",
        "website": None,
        "phonenumber": "11 3695-5000",
        "fax": None,
        "email": None,
        "admin_email": "tatianno.alves@gnew.com.br",
        "admin_email_name": "Tatianno",
        "admin_reply": None,
        "admin_reply_name": None,
        "notification_subject_tag": None,
        "ldap_dn": None,
        "tag": None,
        "authldaps_id": 0,
        "mail_domain": None,
        "entity_ldapfilter": None,
        "mailing_signature": None,
        "cartridges_alert_repeat": -2,
        "consumables_alert_repeat": -2,
        "use_licenses_alert": -2,
        "send_licenses_alert_before_delay": -2,
        "use_certificates_alert": -2,
        "send_certificates_alert_before_delay": -2,
        "use_contracts_alert": -2,
        "send_contracts_alert_before_delay": -2,
        "use_infocoms_alert": -2,
        "send_infocoms_alert_before_delay": -2,
        "use_reservations_alert": -2,
        "autoclose_delay": -2,
        "notclosed_delay": -2,
        "calendars_id": -2,
        "auto_assign_mode": -2,
        "tickettype": -2,
        "max_closedate": "2019-03-23 11:15:14",
        "inquest_config": -2,
        "inquest_rate": 0,
        "inquest_delay": -10,
        "inquest_URL": None,
        "autofill_warranty_date": -2,
        "autofill_use_date": -2,
        "autofill_buy_date": -2,
        "autofill_delivery_date": -2,
        "autofill_order_date": -2,
        "tickettemplates_id": -2,
        "entities_id_software": -2,
        "default_contract_alert": -2,
        "default_infocom_alert": -2,
        "default_cartridges_alarm_threshold": -2,
        "default_consumables_alarm_threshold": -2,
        "delay_send_emails": -2,
        "is_notif_enable_default": -2,
        "inquest_duration": 0,
        "date_mod": "2024-11-07 19:30:51",
        "date_creation": "2019-03-23 11:15:14",
        "autofill_decommission_date": -2,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "Calendar",
                "href": "https://glpi-teste.com.br/apirest.php/Calendar/-2"
            },
            {
                "rel": "TicketTemplate",
                "href": "https://glpi-teste.com.br/apirest.php/TicketTemplate/-2"
            },
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/-2"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/6/Document_Item/"
            }
        ]
    },
    {
        "id": 7,
        "name": "ACEEX PROCESSAMENTO DE DADOS LTDA",
        "entities_id": 0,
        "completename": "GNEW > ACEEX PROCESSAMENTO DE DADOS LTDA",
        "comment": "POSSUI CONTRATO TDM",
        "level": 2,
        "sons_cache": "{\"7\":\"7\"}",
        "ancestors_cache": "[\"0\"]",
        "address": "AV DOM PEDRO II, 1641 SL 14 \r\nCAMPESTRE",
        "postcode": 9080111,
        "town": "SANTO ANDRÉ",
        "state": "SP",
        "country": "BRASIL",
        "website": None,
        "phonenumber": None,
        "fax": None,
        "email": None,
        "admin_email": None,
        "admin_email_name": None,
        "admin_reply": None,
        "admin_reply_name": None,
        "notification_subject_tag": None,
        "ldap_dn": None,
        "tag": 2318817000138,
        "authldaps_id": 0,
        "mail_domain": None,
        "entity_ldapfilter": None,
        "mailing_signature": None,
        "cartridges_alert_repeat": -2,
        "consumables_alert_repeat": -2,
        "use_licenses_alert": -2,
        "send_licenses_alert_before_delay": -2,
        "use_certificates_alert": -2,
        "send_certificates_alert_before_delay": -2,
        "use_contracts_alert": -2,
        "send_contracts_alert_before_delay": -2,
        "use_infocoms_alert": -2,
        "send_infocoms_alert_before_delay": -2,
        "use_reservations_alert": -2,
        "autoclose_delay": -2,
        "notclosed_delay": -2,
        "calendars_id": -2,
        "auto_assign_mode": -2,
        "tickettype": -2,
        "max_closedate": "2019-03-23 11:18:18",
        "inquest_config": -2,
        "inquest_rate": 0,
        "inquest_delay": -10,
        "inquest_URL": None,
        "autofill_warranty_date": -2,
        "autofill_use_date": -2,
        "autofill_buy_date": -2,
        "autofill_delivery_date": -2,
        "autofill_order_date": -2,
        "tickettemplates_id": -2,
        "entities_id_software": -2,
        "default_contract_alert": -2,
        "default_infocom_alert": -2,
        "default_cartridges_alarm_threshold": -2,
        "default_consumables_alarm_threshold": -2,
        "delay_send_emails": -2,
        "is_notif_enable_default": -2,
        "inquest_duration": 0,
        "date_mod": "2024-08-22 14:33:27",
        "date_creation": "2019-03-23 11:18:18",
        "autofill_decommission_date": -2,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "Calendar",
                "href": "https://glpi-teste.com.br/apirest.php/Calendar/-2"
            },
            {
                "rel": "TicketTemplate",
                "href": "https://glpi-teste.com.br/apirest.php/TicketTemplate/-2"
            },
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/-2"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/7/Document_Item/"
            }
        ]
    },
    {
        "id": 8,
        "name": "ASSOCIACAO DOS OFICIAIS MILITARES DO ESTADO DE SAO PAULO",
        "entities_id": 0,
        "completename": "GNEW > ASSOCIACAO DOS OFICIAIS MILITARES DO ESTADO DE SAO PAULO",
        "comment": "POSSUI CONTRATO TDM",
        "level": 2,
        "sons_cache": "{\"8\":\"8\"}",
        "ancestors_cache": "[\"0\"]",
        "address": "R TABATINGUERA, 278\r\nCENTRO",
        "postcode": 1020000,
        "town": "SÃO PAULO",
        "state": "SP",
        "country": "BRASIL",
        "website": None,
        "phonenumber": None,
        "fax": None,
        "email": None,
        "admin_email": None,
        "admin_email_name": None,
        "admin_reply": None,
        "admin_reply_name": None,
        "notification_subject_tag": None,
        "ldap_dn": None,
        "tag": 62323563000178,
        "authldaps_id": 0,
        "mail_domain": None,
        "entity_ldapfilter": None,
        "mailing_signature": None,
        "cartridges_alert_repeat": -2,
        "consumables_alert_repeat": -2,
        "use_licenses_alert": -2,
        "send_licenses_alert_before_delay": -2,
        "use_certificates_alert": -2,
        "send_certificates_alert_before_delay": -2,
        "use_contracts_alert": -2,
        "send_contracts_alert_before_delay": -2,
        "use_infocoms_alert": -2,
        "send_infocoms_alert_before_delay": -2,
        "use_reservations_alert": -2,
        "autoclose_delay": -2,
        "notclosed_delay": -2,
        "calendars_id": -2,
        "auto_assign_mode": -2,
        "tickettype": -2,
        "max_closedate": "2019-03-23 11:20:31",
        "inquest_config": -2,
        "inquest_rate": 0,
        "inquest_delay": -10,
        "inquest_URL": None,
        "autofill_warranty_date": -2,
        "autofill_use_date": -2,
        "autofill_buy_date": -2,
        "autofill_delivery_date": -2,
        "autofill_order_date": -2,
        "tickettemplates_id": -2,
        "entities_id_software": -2,
        "default_contract_alert": -2,
        "default_infocom_alert": -2,
        "default_cartridges_alarm_threshold": -2,
        "default_consumables_alarm_threshold": -2,
        "delay_send_emails": -2,
        "is_notif_enable_default": -2,
        "inquest_duration": 0,
        "date_mod": "2024-08-23 09:03:17",
        "date_creation": "2019-03-23 11:20:31",
        "autofill_decommission_date": -2,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "Calendar",
                "href": "https://glpi-teste.com.br/apirest.php/Calendar/-2"
            },
            {
                "rel": "TicketTemplate",
                "href": "https://glpi-teste.com.br/apirest.php/TicketTemplate/-2"
            },
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/-2"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/8/Document_Item/"
            }
        ]
    },
    {
        "id": 9,
        "name": "AO ARCO IRIS RECREACAO S/S LTDA",
        "entities_id": 0,
        "completename": "GNEW > AO ARCO IRIS RECREACAO S/S LTDA",
        "comment": "PABX EM NUVEM\r\nCONTRATO SOMENTE COM SUPORTE REMOTO",
        "level": 2,
        "sons_cache": "{\"9\":\"9\"}",
        "ancestors_cache": "[\"0\"]",
        "address": "EST DOS BORGES, 6051\r\nBARRINHA",
        "postcode": 6890000,
        "town": "SAO LOURENCO DA SERRA",
        "state": "SAO PAULO",
        "country": "BRASIL",
        "website": None,
        "phonenumber": "11 3071-0061",
        "fax": None,
        "email": None,
        "admin_email": None,
        "admin_email_name": None,
        "admin_reply": None,
        "admin_reply_name": None,
        "notification_subject_tag": None,
        "ldap_dn": None,
        "tag": None,
        "authldaps_id": 0,
        "mail_domain": None,
        "entity_ldapfilter": None,
        "mailing_signature": None,
        "cartridges_alert_repeat": -2,
        "consumables_alert_repeat": -2,
        "use_licenses_alert": -2,
        "send_licenses_alert_before_delay": -2,
        "use_certificates_alert": -2,
        "send_certificates_alert_before_delay": -2,
        "use_contracts_alert": -2,
        "send_contracts_alert_before_delay": -2,
        "use_infocoms_alert": -2,
        "send_infocoms_alert_before_delay": -2,
        "use_reservations_alert": -2,
        "autoclose_delay": -2,
        "notclosed_delay": -2,
        "calendars_id": -2,
        "auto_assign_mode": -2,
        "tickettype": -2,
        "max_closedate": "2019-03-23 11:23:32",
        "inquest_config": -2,
        "inquest_rate": 0,
        "inquest_delay": -10,
        "inquest_URL": None,
        "autofill_warranty_date": -2,
        "autofill_use_date": -2,
        "autofill_buy_date": -2,
        "autofill_delivery_date": -2,
        "autofill_order_date": -2,
        "tickettemplates_id": -2,
        "entities_id_software": -2,
        "default_contract_alert": -2,
        "default_infocom_alert": -2,
        "default_cartridges_alarm_threshold": -2,
        "default_consumables_alarm_threshold": -2,
        "delay_send_emails": -2,
        "is_notif_enable_default": -2,
        "inquest_duration": 0,
        "date_mod": "2019-03-23 11:25:21",
        "date_creation": "2019-03-23 11:23:32",
        "autofill_decommission_date": -2,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "Calendar",
                "href": "https://glpi-teste.com.br/apirest.php/Calendar/-2"
            },
            {
                "rel": "TicketTemplate",
                "href": "https://glpi-teste.com.br/apirest.php/TicketTemplate/-2"
            },
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/-2"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/9/Document_Item/"
            }
        ]
    },
    {
        "id": 10,
        "name": "MIDIA 123 SERVICOS DE PUBLICIDADE VIA INTERNET LTDA",
        "entities_id": 0,
        "completename": "GNEW > MIDIA 123 SERVICOS DE PUBLICIDADE VIA INTERNET LTDA",
        "comment": "BLINKS",
        "level": 2,
        "sons_cache": "{\"10\":\"10\"}",
        "ancestors_cache": "[\"0\"]",
        "address": "R PADRE JOAO MANUEL, 923 4 ANDAR\r\nCERQUEIRA CESAR",
        "postcode": None,
        "town": "SAO PAULO",
        "state": "SP",
        "country": "BRASIL",
        "website": None,
        "phonenumber": "11 4097-5169",
        "fax": None,
        "email": None,
        "admin_email": None,
        "admin_email_name": None,
        "admin_reply": None,
        "admin_reply_name": None,
        "notification_subject_tag": None,
        "ldap_dn": None,
        "tag": None,
        "authldaps_id": 0,
        "mail_domain": None,
        "entity_ldapfilter": None,
        "mailing_signature": None,
        "cartridges_alert_repeat": -2,
        "consumables_alert_repeat": -2,
        "use_licenses_alert": -2,
        "send_licenses_alert_before_delay": -2,
        "use_certificates_alert": -2,
        "send_certificates_alert_before_delay": -2,
        "use_contracts_alert": -2,
        "send_contracts_alert_before_delay": -2,
        "use_infocoms_alert": -2,
        "send_infocoms_alert_before_delay": -2,
        "use_reservations_alert": -2,
        "autoclose_delay": -2,
        "notclosed_delay": -2,
        "calendars_id": -2,
        "auto_assign_mode": -2,
        "tickettype": -2,
        "max_closedate": "2019-03-23 11:28:04",
        "inquest_config": -2,
        "inquest_rate": 0,
        "inquest_delay": -10,
        "inquest_URL": None,
        "autofill_warranty_date": -2,
        "autofill_use_date": -2,
        "autofill_buy_date": -2,
        "autofill_delivery_date": -2,
        "autofill_order_date": -2,
        "tickettemplates_id": -2,
        "entities_id_software": -2,
        "default_contract_alert": -2,
        "default_infocom_alert": -2,
        "default_cartridges_alarm_threshold": -2,
        "default_consumables_alarm_threshold": -2,
        "delay_send_emails": -2,
        "is_notif_enable_default": -2,
        "inquest_duration": 0,
        "date_mod": "2019-03-23 11:29:07",
        "date_creation": "2019-03-23 11:28:04",
        "autofill_decommission_date": -2,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "Calendar",
                "href": "https://glpi-teste.com.br/apirest.php/Calendar/-2"
            },
            {
                "rel": "TicketTemplate",
                "href": "https://glpi-teste.com.br/apirest.php/TicketTemplate/-2"
            },
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/-2"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/10/Document_Item/"
            }
        ]
    },
    {
        "id": 11,
        "name": "BRASIL BIO FUELS S.A.",
        "entities_id": 0,
        "completename": "GNEW > BRASIL BIO FUELS S.A.",
        "comment": "",
        "level": 2,
        "sons_cache": "{\"11\":\"11\"}",
        "ancestors_cache": "[\"0\"]",
        "address": "RUA BELA CINTRA, 904\r\nCERQUEIRA CESAR",
        "postcode": None,
        "town": "SAO PAULO",
        "state": "SP",
        "country": "BRASIL",
        "website": None,
        "phonenumber": "11 2770-2000",
        "fax": None,
        "email": None,
        "admin_email": None,
        "admin_email_name": None,
        "admin_reply": None,
        "admin_reply_name": None,
        "notification_subject_tag": None,
        "ldap_dn": None,
        "tag": 9478309000670,
        "authldaps_id": 0,
        "mail_domain": None,
        "entity_ldapfilter": None,
        "mailing_signature": None,
        "cartridges_alert_repeat": -2,
        "consumables_alert_repeat": -2,
        "use_licenses_alert": -2,
        "send_licenses_alert_before_delay": -2,
        "use_certificates_alert": -2,
        "send_certificates_alert_before_delay": -2,
        "use_contracts_alert": -2,
        "send_contracts_alert_before_delay": -2,
        "use_infocoms_alert": -2,
        "send_infocoms_alert_before_delay": -2,
        "use_reservations_alert": -2,
        "autoclose_delay": -2,
        "notclosed_delay": -2,
        "calendars_id": -2,
        "auto_assign_mode": -2,
        "tickettype": -2,
        "max_closedate": "2019-03-23 11:29:50",
        "inquest_config": -2,
        "inquest_rate": 0,
        "inquest_delay": -10,
        "inquest_URL": None,
        "autofill_warranty_date": -2,
        "autofill_use_date": -2,
        "autofill_buy_date": -2,
        "autofill_delivery_date": -2,
        "autofill_order_date": -2,
        "tickettemplates_id": -2,
        "entities_id_software": -2,
        "default_contract_alert": -2,
        "default_infocom_alert": -2,
        "default_cartridges_alarm_threshold": -2,
        "default_consumables_alarm_threshold": -2,
        "delay_send_emails": -2,
        "is_notif_enable_default": -2,
        "inquest_duration": 0,
        "date_mod": "2024-08-22 17:26:37",
        "date_creation": "2019-03-23 11:29:50",
        "autofill_decommission_date": -2,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "Calendar",
                "href": "https://glpi-teste.com.br/apirest.php/Calendar/-2"
            },
            {
                "rel": "TicketTemplate",
                "href": "https://glpi-teste.com.br/apirest.php/TicketTemplate/-2"
            },
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/-2"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/11/Document_Item/"
            }
        ]
    },
    {
        "id": 12,
        "name": "BURKE E.PORTER IND E COMERCIO LTDA - EPP",
        "entities_id": 0,
        "completename": "GNEW > BURKE E.PORTER IND E COMERCIO LTDA - EPP",
        "comment": "",
        "level": 2,
        "sons_cache": "{\"12\":\"12\"}",
        "ancestors_cache": "[\"0\"]",
        "address": "R PROF WANDA PERSEGUIM, 10\r\nVL SAO FRANCISCO",
        "postcode": None,
        "town": "SAO PAUOL",
        "state": "SP",
        "country": "BRASIL",
        "website": None,
        "phonenumber": "11 5183-4966",
        "fax": None,
        "email": None,
        "admin_email": None,
        "admin_email_name": None,
        "admin_reply": None,
        "admin_reply_name": None,
        "notification_subject_tag": None,
        "ldap_dn": None,
        "tag": None,
        "authldaps_id": 0,
        "mail_domain": None,
        "entity_ldapfilter": None,
        "mailing_signature": None,
        "cartridges_alert_repeat": -2,
        "consumables_alert_repeat": -2,
        "use_licenses_alert": -2,
        "send_licenses_alert_before_delay": -2,
        "use_certificates_alert": -2,
        "send_certificates_alert_before_delay": -2,
        "use_contracts_alert": -2,
        "send_contracts_alert_before_delay": -2,
        "use_infocoms_alert": -2,
        "send_infocoms_alert_before_delay": -2,
        "use_reservations_alert": -2,
        "autoclose_delay": -2,
        "notclosed_delay": -2,
        "calendars_id": -2,
        "auto_assign_mode": -2,
        "tickettype": -2,
        "max_closedate": "2019-03-23 11:33:49",
        "inquest_config": -2,
        "inquest_rate": 0,
        "inquest_delay": -10,
        "inquest_URL": None,
        "autofill_warranty_date": -2,
        "autofill_use_date": -2,
        "autofill_buy_date": -2,
        "autofill_delivery_date": -2,
        "autofill_order_date": -2,
        "tickettemplates_id": -2,
        "entities_id_software": -2,
        "default_contract_alert": -2,
        "default_infocom_alert": -2,
        "default_cartridges_alarm_threshold": -2,
        "default_consumables_alarm_threshold": -2,
        "delay_send_emails": -2,
        "is_notif_enable_default": -2,
        "inquest_duration": 0,
        "date_mod": "2019-03-23 11:34:59",
        "date_creation": "2019-03-23 11:33:49",
        "autofill_decommission_date": -2,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "Calendar",
                "href": "https://glpi-teste.com.br/apirest.php/Calendar/-2"
            },
            {
                "rel": "TicketTemplate",
                "href": "https://glpi-teste.com.br/apirest.php/TicketTemplate/-2"
            },
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/-2"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/12/Document_Item/"
            }
        ]
    },
    {
        "id": 13,
        "name": "TOSTE, MARQUES E MOUAOUAD SOCIEDADE DE ADVOGADOS.",
        "entities_id": 0,
        "completename": "GNEW > TOSTE, MARQUES E MOUAOUAD SOCIEDADE DE ADVOGADOS.",
        "comment": "CAMPOS BICUDO",
        "level": 2,
        "sons_cache": "{\"13\":\"13\"}",
        "ancestors_cache": "[\"0\"]",
        "address": "R HELENA 280\r\nVL OLIMPIA",
        "postcode": None,
        "town": "SAO PAULO",
        "state": "SP",
        "country": "BRASIL",
        "website": None,
        "phonenumber": "11 3168-1166",
        "fax": None,
        "email": None,
        "admin_email": None,
        "admin_email_name": None,
        "admin_reply": None,
        "admin_reply_name": None,
        "notification_subject_tag": None,
        "ldap_dn": None,
        "tag": 24960469000130,
        "authldaps_id": 0,
        "mail_domain": None,
        "entity_ldapfilter": None,
        "mailing_signature": None,
        "cartridges_alert_repeat": -2,
        "consumables_alert_repeat": -2,
        "use_licenses_alert": -2,
        "send_licenses_alert_before_delay": -2,
        "use_certificates_alert": -2,
        "send_certificates_alert_before_delay": -2,
        "use_contracts_alert": -2,
        "send_contracts_alert_before_delay": -2,
        "use_infocoms_alert": -2,
        "send_infocoms_alert_before_delay": -2,
        "use_reservations_alert": -2,
        "autoclose_delay": -2,
        "notclosed_delay": -2,
        "calendars_id": -2,
        "auto_assign_mode": -2,
        "tickettype": -2,
        "max_closedate": "2019-03-23 11:35:43",
        "inquest_config": -2,
        "inquest_rate": 0,
        "inquest_delay": -10,
        "inquest_URL": None,
        "autofill_warranty_date": -2,
        "autofill_use_date": -2,
        "autofill_buy_date": -2,
        "autofill_delivery_date": -2,
        "autofill_order_date": -2,
        "tickettemplates_id": -2,
        "entities_id_software": -2,
        "default_contract_alert": -2,
        "default_infocom_alert": -2,
        "default_cartridges_alarm_threshold": -2,
        "default_consumables_alarm_threshold": -2,
        "delay_send_emails": -2,
        "is_notif_enable_default": -2,
        "inquest_duration": 0,
        "date_mod": "2024-08-22 10:12:16",
        "date_creation": "2019-03-23 11:35:43",
        "autofill_decommission_date": -2,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "Calendar",
                "href": "https://glpi-teste.com.br/apirest.php/Calendar/-2"
            },
            {
                "rel": "TicketTemplate",
                "href": "https://glpi-teste.com.br/apirest.php/TicketTemplate/-2"
            },
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/-2"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/13/Document_Item/"
            }
        ]
    },
    {
        "id": 14,
        "name": "ADMINISTRADORA DE CARTAO DE TODOS SAO MATEUS LTDA - ME",
        "entities_id": 0,
        "completename": "GNEW > ADMINISTRADORA DE CARTAO DE TODOS SAO MATEUS LTDA - ME",
        "comment": "",
        "level": 2,
        "sons_cache": "{\"14\":\"14\"}",
        "ancestors_cache": "[\"0\"]",
        "address": "AV SAPOPEMBA, 16061\r\nJD RODOLFO PIRANI",
        "postcode": None,
        "town": "SAO PAULO",
        "state": "SP",
        "country": "BRASIL",
        "website": None,
        "phonenumber": None,
        "fax": None,
        "email": None,
        "admin_email": None,
        "admin_email_name": None,
        "admin_reply": None,
        "admin_reply_name": None,
        "notification_subject_tag": None,
        "ldap_dn": None,
        "tag": None,
        "authldaps_id": 0,
        "mail_domain": None,
        "entity_ldapfilter": None,
        "mailing_signature": None,
        "cartridges_alert_repeat": -2,
        "consumables_alert_repeat": -2,
        "use_licenses_alert": -2,
        "send_licenses_alert_before_delay": -2,
        "use_certificates_alert": -2,
        "send_certificates_alert_before_delay": -2,
        "use_contracts_alert": -2,
        "send_contracts_alert_before_delay": -2,
        "use_infocoms_alert": -2,
        "send_infocoms_alert_before_delay": -2,
        "use_reservations_alert": -2,
        "autoclose_delay": -2,
        "notclosed_delay": -2,
        "calendars_id": -2,
        "auto_assign_mode": -2,
        "tickettype": -2,
        "max_closedate": "2019-03-23 11:37:24",
        "inquest_config": -2,
        "inquest_rate": 0,
        "inquest_delay": -10,
        "inquest_URL": None,
        "autofill_warranty_date": -2,
        "autofill_use_date": -2,
        "autofill_buy_date": -2,
        "autofill_delivery_date": -2,
        "autofill_order_date": -2,
        "tickettemplates_id": -2,
        "entities_id_software": -2,
        "default_contract_alert": -2,
        "default_infocom_alert": -2,
        "default_cartridges_alarm_threshold": -2,
        "default_consumables_alarm_threshold": -2,
        "delay_send_emails": -2,
        "is_notif_enable_default": -2,
        "inquest_duration": 0,
        "date_mod": "2019-03-23 11:38:24",
        "date_creation": "2019-03-23 11:37:24",
        "autofill_decommission_date": -2,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "Calendar",
                "href": "https://glpi-teste.com.br/apirest.php/Calendar/-2"
            },
            {
                "rel": "TicketTemplate",
                "href": "https://glpi-teste.com.br/apirest.php/TicketTemplate/-2"
            },
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/-2"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/14/Document_Item/"
            }
        ]
    },
    {
        "id": 15,
        "name": "CONEXAO DIGITAL TELECOMUNICACOES LTDA - EPP",
        "entities_id": 0,
        "completename": "GNEW > CONEXAO DIGITAL TELECOMUNICACOES LTDA - EPP",
        "comment": "",
        "level": 2,
        "sons_cache": None,
        "ancestors_cache": "[\"0\"]",
        "address": "AV VEREADOR NARCISO YAGUE GUIMARAES, 1145\r\nVILA PARTENIO",
        "postcode": None,
        "town": "MOGI DAS CRUZES",
        "state": "SP",
        "country": "BRASIL",
        "website": None,
        "phonenumber": None,
        "fax": None,
        "email": None,
        "admin_email": None,
        "admin_email_name": None,
        "admin_reply": None,
        "admin_reply_name": None,
        "notification_subject_tag": None,
        "ldap_dn": None,
        "tag": None,
        "authldaps_id": 0,
        "mail_domain": None,
        "entity_ldapfilter": None,
        "mailing_signature": None,
        "cartridges_alert_repeat": -2,
        "consumables_alert_repeat": -2,
        "use_licenses_alert": -2,
        "send_licenses_alert_before_delay": -2,
        "use_certificates_alert": -2,
        "send_certificates_alert_before_delay": -2,
        "use_contracts_alert": -2,
        "send_contracts_alert_before_delay": -2,
        "use_infocoms_alert": -2,
        "send_infocoms_alert_before_delay": -2,
        "use_reservations_alert": -2,
        "autoclose_delay": -2,
        "notclosed_delay": -2,
        "calendars_id": -2,
        "auto_assign_mode": -2,
        "tickettype": -2,
        "max_closedate": "2019-03-23 11:39:07",
        "inquest_config": -2,
        "inquest_rate": 0,
        "inquest_delay": -10,
        "inquest_URL": None,
        "autofill_warranty_date": -2,
        "autofill_use_date": -2,
        "autofill_buy_date": -2,
        "autofill_delivery_date": -2,
        "autofill_order_date": -2,
        "tickettemplates_id": -2,
        "entities_id_software": -2,
        "default_contract_alert": -2,
        "default_infocom_alert": -2,
        "default_cartridges_alarm_threshold": -2,
        "default_consumables_alarm_threshold": -2,
        "delay_send_emails": -2,
        "is_notif_enable_default": -2,
        "inquest_duration": 0,
        "date_mod": "2019-03-23 11:39:55",
        "date_creation": "2019-03-23 11:39:07",
        "autofill_decommission_date": -2,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "Calendar",
                "href": "https://glpi-teste.com.br/apirest.php/Calendar/-2"
            },
            {
                "rel": "TicketTemplate",
                "href": "https://glpi-teste.com.br/apirest.php/TicketTemplate/-2"
            },
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/-2"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/15/Document_Item/"
            }
        ]
    }
]