USER_RESPONSE = {
    "id": 8,
    "name": "tatianno",
    "phone": "",
    "phone2": "",
    "mobile": "",
    "realname": "Alves",
    "firstname": "Tatianno",
    "locations_id": 0,
    "language": None,
    "use_mode": 0,
    "list_limit": None,
    "is_active": 1,
    "comment": "",
    "auths_id": 0,
    "authtype": 1,
    "last_login": "2024-11-07 19:19:24",
    "date_mod": "2024-11-05 18:56:41",
    "date_sync": None,
    "is_deleted": 0,
    "profiles_id": 4,
    "entities_id": 0,
    "usertitles_id": 0,
    "usercategories_id": 1,
    "date_format": None,
    "number_format": None,
    "names_format": None,
    "csv_delimiter": None,
    "is_ids_visible": None,
    "use_flat_dropdowntree": None,
    "show_jobs_at_login": None,
    "priority_1": None,
    "priority_2": None,
    "priority_3": None,
    "priority_4": None,
    "priority_5": None,
    "priority_6": None,
    "followup_private": None,
    "task_private": None,
    "default_requesttypes_id": None,
    "password_forget_token": None,
    "password_forget_token_date": None,
    "user_dn": None,
    "registration_number": "",
    "show_count_on_tabs": None,
    "refresh_ticket_list": None,
    "set_default_tech": None,
    "personal_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "personal_token_date": "2019-03-22 21:46:55",
    "api_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "api_token_date": "2021-03-19 08:20:33",
    "cookie_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "cookie_token_date": "2024-11-05 18:56:41",
    "display_count_on_home": None,
    "notification_to_myself": None,
    "duedateok_color": None,
    "duedatewarning_color": None,
    "duedatecritical_color": None,
    "duedatewarning_less": None,
    "duedatecritical_less": None,
    "duedatewarning_unit": None,
    "duedatecritical_unit": None,
    "display_options": None,
    "is_deleted_ldap": 0,
    "pdffont": None,
    "picture": None,
    "begin_date": None,
    "end_date": None,
    "keep_devices_when_purging_item": None,
    "privatebookmarkorder": "[1]",
    "backcreated": None,
    "task_state": None,
    "layout": None,
    "palette": None,
    "set_default_requester": None,
    "lock_autolock_mode": None,
    "lock_directunlock_notification": None,
    "date_creation": "2019-03-22 20:04:18",
    "highcontrast_css": None,
    "plannings": "{\"filters\":{\"Reminder\":{\"color\":\"#E94A31\",\"display\":false,\"type\":\"event_filter\"},\"TicketTask\":{\"color\":\"#5174F2\",\"display\":true,\"type\":\"event_filter\"},\"ProjectTask\":{\"color\":\"#51C9F2\",\"display\":true,\"type\":\"event_filter\"},\"ChangeTask\":{\"color\":\"#E94A31\",\"display\":true,\"type\":\"event_filter\"},\"ProblemTask\":{\"color\":\"#5174F2\",\"display\":true,\"type\":\"event_filter\"}},\"plannings\":{\"user_8\":{\"color\":\"#FFEEC4\",\"display\":true,\"type\":\"user\"}}}",
    "sync_field": None,
    "groups_id": 1,
    "users_id_supervisor": 0,
    "links": [
        {
            "rel": "Profile",
            "href": "https://teste-glpi.com.br/apirest.php/Profile/4"
        },
        {
            "rel": "Entity",
            "href": "https://teste-glpi.com.br/apirest.php/Entity/0"
        },
        {
            "rel": "UserCategory",
            "href": "https://teste-glpi.com.br/apirest.php/UserCategory/1"
        },
        {
            "rel": "Group",
            "href": "https://teste-glpi.com.br/apirest.php/Group/1"
        },
        {
            "rel": "Document_Item",
            "href": "https://teste-glpi.com.br/apirest.php/User/8/Document_Item/"
        }
    ]
}

USERS_RESPONSE = [
    {
        "id": 8,
        "name": "tatianno",
        "phone": "",
        "phone2": "",
        "mobile": "",
        "realname": "Alves",
        "firstname": "Tatianno",
        "locations_id": 0,
        "language": None,
        "use_mode": 0,
        "list_limit": None,
        "is_active": 1,
        "comment": "",
        "auths_id": 0,
        "authtype": 1,
        "last_login": "2024-11-08 16:45:02",
        "date_mod": "2024-11-05 18:56:41",
        "date_sync": None,
        "is_deleted": 0,
        "profiles_id": 4,
        "entities_id": 0,
        "usertitles_id": 0,
        "usercategories_id": 1,
        "date_format": None,
        "number_format": None,
        "names_format": None,
        "csv_delimiter": None,
        "is_ids_visible": None,
        "use_flat_dropdowntree": None,
        "show_jobs_at_login": None,
        "priority_1": None,
        "priority_2": None,
        "priority_3": None,
        "priority_4": None,
        "priority_5": None,
        "priority_6": None,
        "followup_private": None,
        "task_private": None,
        "default_requesttypes_id": None,
        "password_forget_token": None,
        "password_forget_token_date": None,
        "user_dn": None,
        "registration_number": "",
        "show_count_on_tabs": None,
        "refresh_ticket_list": None,
        "set_default_tech": None,
        "personal_token": "GNXIDzSXhlsniYIw5tRsdtAVc2xsw81sk6fzY6P4",
        "personal_token_date": "2019-03-22 21:46:55",
        "api_token": "refx94yoMgyadJVoxoE8QSYQ0j3XLwkCziHdYf4k",
        "api_token_date": "2021-03-19 08:20:33",
        "cookie_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "cookie_token_date": "2024-11-05 18:56:41",
        "display_count_on_home": None,
        "notification_to_myself": None,
        "duedateok_color": None,
        "duedatewarning_color": None,
        "duedatecritical_color": None,
        "duedatewarning_less": None,
        "duedatecritical_less": None,
        "duedatewarning_unit": None,
        "duedatecritical_unit": None,
        "display_options": None,
        "is_deleted_ldap": 0,
        "pdffont": None,
        "picture": None,
        "begin_date": None,
        "end_date": None,
        "keep_devices_when_purging_item": None,
        "privatebookmarkorder": "[1]",
        "backcreated": None,
        "task_state": None,
        "layout": None,
        "palette": None,
        "set_default_requester": None,
        "lock_autolock_mode": None,
        "lock_directunlock_notification": None,
        "date_creation": "2019-03-22 20:04:18",
        "highcontrast_css": None,
        "plannings": "{\"filters\":{\"Reminder\":{\"color\":\"#E94A31\",\"display\":false,\"type\":\"event_filter\"},\"TicketTask\":{\"color\":\"#5174F2\",\"display\":true,\"type\":\"event_filter\"},\"ProjectTask\":{\"color\":\"#51C9F2\",\"display\":true,\"type\":\"event_filter\"},\"ChangeTask\":{\"color\":\"#E94A31\",\"display\":true,\"type\":\"event_filter\"},\"ProblemTask\":{\"color\":\"#5174F2\",\"display\":true,\"type\":\"event_filter\"}},\"plannings\":{\"user_8\":{\"color\":\"#FFEEC4\",\"display\":true,\"type\":\"user\"}}}",
        "sync_field": None,
        "groups_id": 1,
        "users_id_supervisor": 0,
        "links": [
            {
                "rel": "Profile",
                "href": "https://glpi-teste.com.br/apirest.php/Profile/4"
            },
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "UserCategory",
                "href": "https://glpi-teste.com.br/apirest.php/UserCategory/1"
            },
            {
                "rel": "Group",
                "href": "https://glpi-teste.com.br/apirest.php/Group/1"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/User/8/Document_Item/"
            }
        ]
    },
    {
        "id": 9,
        "name": "guilherme",
        "phone": "",
        "phone2": "",
        "mobile": "",
        "realname": "Carvalho",
        "firstname": "Guilherme",
        "locations_id": 0,
        "language": None,
        "use_mode": 0,
        "list_limit": None,
        "is_active": 1,
        "comment": "",
        "auths_id": 0,
        "authtype": 1,
        "last_login": "2024-11-08 09:01:32",
        "date_mod": "2024-11-05 09:08:25",
        "date_sync": None,
        "is_deleted": 0,
        "profiles_id": 0,
        "entities_id": 0,
        "usertitles_id": 0,
        "usercategories_id": 1,
        "date_format": None,
        "number_format": None,
        "names_format": None,
        "csv_delimiter": None,
        "is_ids_visible": None,
        "use_flat_dropdowntree": None,
        "show_jobs_at_login": None,
        "priority_1": None,
        "priority_2": None,
        "priority_3": None,
        "priority_4": None,
        "priority_5": None,
        "priority_6": None,
        "followup_private": None,
        "task_private": None,
        "default_requesttypes_id": None,
        "password_forget_token": None,
        "password_forget_token_date": None,
        "user_dn": None,
        "registration_number": "",
        "show_count_on_tabs": None,
        "refresh_ticket_list": None,
        "set_default_tech": None,
        "personal_token": "nHeBtjHTjsAXlUOzWOcDIUlO4Zke0tH1DTkAb6pD",
        "personal_token_date": "2022-01-26 09:19:37",
        "api_token": None,
        "api_token_date": None,
        "cookie_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "cookie_token_date": "2024-11-05 09:08:25",
        "display_count_on_home": None,
        "notification_to_myself": None,
        "duedateok_color": None,
        "duedatewarning_color": None,
        "duedatecritical_color": None,
        "duedatewarning_less": None,
        "duedatecritical_less": None,
        "duedatewarning_unit": None,
        "duedatecritical_unit": None,
        "display_options": None,
        "is_deleted_ldap": 0,
        "pdffont": None,
        "picture": None,
        "begin_date": None,
        "end_date": None,
        "keep_devices_when_purging_item": None,
        "privatebookmarkorder": None,
        "backcreated": None,
        "task_state": None,
        "layout": None,
        "palette": None,
        "set_default_requester": None,
        "lock_autolock_mode": None,
        "lock_directunlock_notification": None,
        "date_creation": "2019-03-22 20:49:13",
        "highcontrast_css": None,
        "plannings": None,
        "sync_field": None,
        "groups_id": 0,
        "users_id_supervisor": 0,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "UserCategory",
                "href": "https://glpi-teste.com.br/apirest.php/UserCategory/1"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/User/9/Document_Item/"
            }
        ]
    },
    {
        "id": 10,
        "name": "caio",
        "phone": "",
        "phone2": "",
        "mobile": "",
        "realname": "Munhoz",
        "firstname": "Caio",
        "locations_id": 0,
        "language": None,
        "use_mode": 0,
        "list_limit": None,
        "is_active": 1,
        "comment": "",
        "auths_id": 0,
        "authtype": 1,
        "last_login": "2024-11-08 10:30:23",
        "date_mod": "2024-11-05 17:03:11",
        "date_sync": None,
        "is_deleted": 0,
        "profiles_id": 0,
        "entities_id": 0,
        "usertitles_id": 0,
        "usercategories_id": 1,
        "date_format": None,
        "number_format": None,
        "names_format": None,
        "csv_delimiter": None,
        "is_ids_visible": None,
        "use_flat_dropdowntree": None,
        "show_jobs_at_login": None,
        "priority_1": None,
        "priority_2": None,
        "priority_3": None,
        "priority_4": None,
        "priority_5": None,
        "priority_6": None,
        "followup_private": None,
        "task_private": None,
        "default_requesttypes_id": None,
        "password_forget_token": None,
        "password_forget_token_date": None,
        "user_dn": None,
        "registration_number": "",
        "show_count_on_tabs": None,
        "refresh_ticket_list": None,
        "set_default_tech": None,
        "personal_token": None,
        "personal_token_date": None,
        "api_token": None,
        "api_token_date": None,
        "cookie_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "cookie_token_date": "2024-11-05 17:03:11",
        "display_count_on_home": None,
        "notification_to_myself": None,
        "duedateok_color": None,
        "duedatewarning_color": None,
        "duedatecritical_color": None,
        "duedatewarning_less": None,
        "duedatecritical_less": None,
        "duedatewarning_unit": None,
        "duedatecritical_unit": None,
        "display_options": None,
        "is_deleted_ldap": 0,
        "pdffont": None,
        "picture": None,
        "begin_date": None,
        "end_date": None,
        "keep_devices_when_purging_item": None,
        "privatebookmarkorder": None,
        "backcreated": None,
        "task_state": None,
        "layout": None,
        "palette": None,
        "set_default_requester": None,
        "lock_autolock_mode": None,
        "lock_directunlock_notification": None,
        "date_creation": "2019-03-23 16:45:00",
        "highcontrast_css": None,
        "plannings": None,
        "sync_field": None,
        "groups_id": 0,
        "users_id_supervisor": 0,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "UserCategory",
                "href": "https://glpi-teste.com.br/apirest.php/UserCategory/1"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/User/10/Document_Item/"
            }
        ]
    },
    {
        "id": 11,
        "name": "abner",
        "phone": "",
        "phone2": "",
        "mobile": "",
        "realname": "Venancio",
        "firstname": "Abner",
        "locations_id": 0,
        "language": None,
        "use_mode": 0,
        "list_limit": None,
        "is_active": 0,
        "comment": "",
        "auths_id": 0,
        "authtype": 1,
        "last_login": "2021-01-12 16:30:47",
        "date_mod": "2021-04-01 09:06:05",
        "date_sync": None,
        "is_deleted": 0,
        "profiles_id": 0,
        "entities_id": 0,
        "usertitles_id": 0,
        "usercategories_id": 1,
        "date_format": None,
        "number_format": None,
        "names_format": None,
        "csv_delimiter": None,
        "is_ids_visible": None,
        "use_flat_dropdowntree": None,
        "show_jobs_at_login": None,
        "priority_1": None,
        "priority_2": None,
        "priority_3": None,
        "priority_4": None,
        "priority_5": None,
        "priority_6": None,
        "followup_private": None,
        "task_private": None,
        "default_requesttypes_id": None,
        "password_forget_token": None,
        "password_forget_token_date": None,
        "user_dn": None,
        "registration_number": "",
        "show_count_on_tabs": None,
        "refresh_ticket_list": None,
        "set_default_tech": None,
        "personal_token": "n4I7B4a5BVy87H7NgPd9dJWayrhp5qvfqa0wNX4b",
        "personal_token_date": "2019-09-02 11:32:22",
        "api_token": None,
        "api_token_date": None,
        "cookie_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "cookie_token_date": "2021-01-11 16:49:08",
        "display_count_on_home": None,
        "notification_to_myself": None,
        "duedateok_color": None,
        "duedatewarning_color": None,
        "duedatecritical_color": None,
        "duedatewarning_less": None,
        "duedatecritical_less": None,
        "duedatewarning_unit": None,
        "duedatecritical_unit": None,
        "display_options": None,
        "is_deleted_ldap": 0,
        "pdffont": None,
        "picture": None,
        "begin_date": None,
        "end_date": None,
        "keep_devices_when_purging_item": None,
        "privatebookmarkorder": None,
        "backcreated": None,
        "task_state": None,
        "layout": None,
        "palette": None,
        "set_default_requester": None,
        "lock_autolock_mode": None,
        "lock_directunlock_notification": None,
        "date_creation": "2019-03-23 16:48:07",
        "highcontrast_css": None,
        "plannings": None,
        "sync_field": None,
        "groups_id": 0,
        "users_id_supervisor": 0,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "UserCategory",
                "href": "https://glpi-teste.com.br/apirest.php/UserCategory/1"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/User/11/Document_Item/"
            }
        ]
    },
    {
        "id": 12,
        "name": "alessandro",
        "phone": "",
        "phone2": "",
        "mobile": "",
        "realname": "Caetano",
        "firstname": "alessandro",
        "locations_id": 0,
        "language": None,
        "use_mode": 0,
        "list_limit": None,
        "is_active": 1,
        "comment": "",
        "auths_id": 0,
        "authtype": 1,
        "last_login": "2024-08-21 16:47:38",
        "date_mod": "2024-08-21 16:47:38",
        "date_sync": None,
        "is_deleted": 0,
        "profiles_id": 0,
        "entities_id": 0,
        "usertitles_id": 0,
        "usercategories_id": 1,
        "date_format": None,
        "number_format": None,
        "names_format": None,
        "csv_delimiter": None,
        "is_ids_visible": None,
        "use_flat_dropdowntree": None,
        "show_jobs_at_login": None,
        "priority_1": None,
        "priority_2": None,
        "priority_3": None,
        "priority_4": None,
        "priority_5": None,
        "priority_6": None,
        "followup_private": None,
        "task_private": None,
        "default_requesttypes_id": None,
        "password_forget_token": "ad40940960a4756d179c1b857ded047fb85ef543",
        "password_forget_token_date": "2024-08-07 16:13:23",
        "user_dn": None,
        "registration_number": "",
        "show_count_on_tabs": None,
        "refresh_ticket_list": None,
        "set_default_tech": None,
        "personal_token": None,
        "personal_token_date": None,
        "api_token": None,
        "api_token_date": None,
        "cookie_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "cookie_token_date": "2024-08-21 16:47:38",
        "display_count_on_home": None,
        "notification_to_myself": None,
        "duedateok_color": None,
        "duedatewarning_color": None,
        "duedatecritical_color": None,
        "duedatewarning_less": None,
        "duedatecritical_less": None,
        "duedatewarning_unit": None,
        "duedatecritical_unit": None,
        "display_options": None,
        "is_deleted_ldap": 0,
        "pdffont": None,
        "picture": None,
        "begin_date": None,
        "end_date": None,
        "keep_devices_when_purging_item": None,
        "privatebookmarkorder": "[2]",
        "backcreated": None,
        "task_state": None,
        "layout": None,
        "palette": None,
        "set_default_requester": None,
        "lock_autolock_mode": None,
        "lock_directunlock_notification": None,
        "date_creation": "2019-03-23 16:49:00",
        "highcontrast_css": None,
        "plannings": None,
        "sync_field": None,
        "groups_id": 0,
        "users_id_supervisor": 0,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "UserCategory",
                "href": "https://glpi-teste.com.br/apirest.php/UserCategory/1"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/User/12/Document_Item/"
            }
        ]
    },
    {
        "id": 13,
        "name": "anderson",
        "phone": "",
        "phone2": "",
        "mobile": "",
        "realname": "Santos",
        "firstname": "Anderson",
        "locations_id": 0,
        "language": None,
        "use_mode": 0,
        "list_limit": None,
        "is_active": 1,
        "comment": "",
        "auths_id": 0,
        "authtype": 1,
        "last_login": "2024-10-02 13:43:27",
        "date_mod": "2024-10-02 13:43:27",
        "date_sync": None,
        "is_deleted": 0,
        "profiles_id": 0,
        "entities_id": 0,
        "usertitles_id": 0,
        "usercategories_id": 1,
        "date_format": None,
        "number_format": None,
        "names_format": None,
        "csv_delimiter": None,
        "is_ids_visible": None,
        "use_flat_dropdowntree": None,
        "show_jobs_at_login": None,
        "priority_1": None,
        "priority_2": None,
        "priority_3": None,
        "priority_4": None,
        "priority_5": None,
        "priority_6": None,
        "followup_private": None,
        "task_private": None,
        "default_requesttypes_id": None,
        "password_forget_token": None,
        "password_forget_token_date": None,
        "user_dn": None,
        "registration_number": "",
        "show_count_on_tabs": None,
        "refresh_ticket_list": None,
        "set_default_tech": None,
        "personal_token": None,
        "personal_token_date": None,
        "api_token": None,
        "api_token_date": None,
        "cookie_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "cookie_token_date": "2024-10-02 13:43:27",
        "display_count_on_home": None,
        "notification_to_myself": None,
        "duedateok_color": None,
        "duedatewarning_color": None,
        "duedatecritical_color": None,
        "duedatewarning_less": None,
        "duedatecritical_less": None,
        "duedatewarning_unit": None,
        "duedatecritical_unit": None,
        "display_options": None,
        "is_deleted_ldap": 0,
        "pdffont": None,
        "picture": None,
        "begin_date": None,
        "end_date": None,
        "keep_devices_when_purging_item": None,
        "privatebookmarkorder": None,
        "backcreated": None,
        "task_state": None,
        "layout": None,
        "palette": None,
        "set_default_requester": None,
        "lock_autolock_mode": None,
        "lock_directunlock_notification": None,
        "date_creation": "2019-03-23 16:50:34",
        "highcontrast_css": None,
        "plannings": None,
        "sync_field": None,
        "groups_id": 0,
        "users_id_supervisor": 0,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "UserCategory",
                "href": "https://glpi-teste.com.br/apirest.php/UserCategory/1"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/User/13/Document_Item/"
            }
        ]
    },
    {
        "id": 14,
        "name": "aldemir",
        "phone": "",
        "phone2": "",
        "mobile": "",
        "realname": "Caetano",
        "firstname": "Aldemir",
        "locations_id": 0,
        "language": None,
        "use_mode": 0,
        "list_limit": None,
        "is_active": 1,
        "comment": "",
        "auths_id": 0,
        "authtype": 1,
        "last_login": "2024-11-08 10:32:58",
        "date_mod": "2024-11-04 11:37:02",
        "date_sync": None,
        "is_deleted": 0,
        "profiles_id": 0,
        "entities_id": 0,
        "usertitles_id": 0,
        "usercategories_id": 1,
        "date_format": None,
        "number_format": None,
        "names_format": None,
        "csv_delimiter": None,
        "is_ids_visible": None,
        "use_flat_dropdowntree": None,
        "show_jobs_at_login": None,
        "priority_1": None,
        "priority_2": None,
        "priority_3": None,
        "priority_4": None,
        "priority_5": None,
        "priority_6": None,
        "followup_private": None,
        "task_private": None,
        "default_requesttypes_id": None,
        "password_forget_token": None,
        "password_forget_token_date": None,
        "user_dn": None,
        "registration_number": "",
        "show_count_on_tabs": None,
        "refresh_ticket_list": None,
        "set_default_tech": None,
        "personal_token": None,
        "personal_token_date": None,
        "api_token": None,
        "api_token_date": None,
        "cookie_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "cookie_token_date": "2024-11-04 11:37:02",
        "display_count_on_home": None,
        "notification_to_myself": None,
        "duedateok_color": None,
        "duedatewarning_color": None,
        "duedatecritical_color": None,
        "duedatewarning_less": None,
        "duedatecritical_less": None,
        "duedatewarning_unit": None,
        "duedatecritical_unit": None,
        "display_options": None,
        "is_deleted_ldap": 0,
        "pdffont": None,
        "picture": None,
        "begin_date": None,
        "end_date": None,
        "keep_devices_when_purging_item": None,
        "privatebookmarkorder": None,
        "backcreated": None,
        "task_state": None,
        "layout": None,
        "palette": None,
        "set_default_requester": None,
        "lock_autolock_mode": None,
        "lock_directunlock_notification": None,
        "date_creation": "2019-03-25 13:11:54",
        "highcontrast_css": None,
        "plannings": None,
        "sync_field": None,
        "groups_id": 0,
        "users_id_supervisor": 0,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "UserCategory",
                "href": "https://glpi-teste.com.br/apirest.php/UserCategory/1"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/User/14/Document_Item/"
            }
        ]
    },
    {
        "id": 17,
        "name": "rodrigo",
        "phone": "",
        "phone2": "",
        "mobile": "",
        "realname": "Souza",
        "firstname": "Rodrigo",
        "locations_id": 0,
        "language": None,
        "use_mode": 0,
        "list_limit": None,
        "is_active": 1,
        "comment": "",
        "auths_id": 0,
        "authtype": 1,
        "last_login": "2022-12-26 11:11:27",
        "date_mod": "2022-12-26 11:11:27",
        "date_sync": None,
        "is_deleted": 0,
        "profiles_id": 0,
        "entities_id": 0,
        "usertitles_id": 0,
        "usercategories_id": 0,
        "date_format": None,
        "number_format": None,
        "names_format": None,
        "csv_delimiter": None,
        "is_ids_visible": None,
        "use_flat_dropdowntree": None,
        "show_jobs_at_login": None,
        "priority_1": None,
        "priority_2": None,
        "priority_3": None,
        "priority_4": None,
        "priority_5": None,
        "priority_6": None,
        "followup_private": None,
        "task_private": None,
        "default_requesttypes_id": None,
        "password_forget_token": None,
        "password_forget_token_date": None,
        "user_dn": None,
        "registration_number": "",
        "show_count_on_tabs": None,
        "refresh_ticket_list": None,
        "set_default_tech": None,
        "personal_token": "irpDCm0S5QPeT1LJyoL4qhdIaSRayUW8wFEjhaZ5",
        "personal_token_date": "2020-11-30 18:01:45",
        "api_token": None,
        "api_token_date": None,
        "cookie_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "cookie_token_date": "2022-12-26 11:11:27",
        "display_count_on_home": None,
        "notification_to_myself": None,
        "duedateok_color": None,
        "duedatewarning_color": None,
        "duedatecritical_color": None,
        "duedatewarning_less": None,
        "duedatecritical_less": None,
        "duedatewarning_unit": None,
        "duedatecritical_unit": None,
        "display_options": None,
        "is_deleted_ldap": 0,
        "pdffont": None,
        "picture": None,
        "begin_date": None,
        "end_date": None,
        "keep_devices_when_purging_item": None,
        "privatebookmarkorder": None,
        "backcreated": None,
        "task_state": None,
        "layout": None,
        "palette": None,
        "set_default_requester": None,
        "lock_autolock_mode": None,
        "lock_directunlock_notification": None,
        "date_creation": "2019-08-22 11:56:16",
        "highcontrast_css": None,
        "plannings": None,
        "sync_field": None,
        "groups_id": 0,
        "users_id_supervisor": 0,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/User/17/Document_Item/"
            }
        ]
    },
    {
        "id": 18,
        "name": "guilherme.henrique",
        "phone": "",
        "phone2": "",
        "mobile": "",
        "realname": "",
        "firstname": "",
        "locations_id": 0,
        "language": None,
        "use_mode": 0,
        "list_limit": None,
        "is_active": 1,
        "comment": "",
        "auths_id": 0,
        "authtype": 1,
        "last_login": "2020-03-19 21:13:21",
        "date_mod": "2020-03-19 00:31:17",
        "date_sync": None,
        "is_deleted": 0,
        "profiles_id": 0,
        "entities_id": 0,
        "usertitles_id": 0,
        "usercategories_id": 0,
        "date_format": None,
        "number_format": None,
        "names_format": None,
        "csv_delimiter": None,
        "is_ids_visible": None,
        "use_flat_dropdowntree": None,
        "show_jobs_at_login": None,
        "priority_1": None,
        "priority_2": None,
        "priority_3": None,
        "priority_4": None,
        "priority_5": None,
        "priority_6": None,
        "followup_private": None,
        "task_private": None,
        "default_requesttypes_id": None,
        "password_forget_token": None,
        "password_forget_token_date": None,
        "user_dn": None,
        "registration_number": "",
        "show_count_on_tabs": None,
        "refresh_ticket_list": None,
        "set_default_tech": None,
        "personal_token": None,
        "personal_token_date": None,
        "api_token": None,
        "api_token_date": None,
        "cookie_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "cookie_token_date": "2020-03-19 00:31:17",
        "display_count_on_home": None,
        "notification_to_myself": None,
        "duedateok_color": None,
        "duedatewarning_color": None,
        "duedatecritical_color": None,
        "duedatewarning_less": None,
        "duedatecritical_less": None,
        "duedatewarning_unit": None,
        "duedatecritical_unit": None,
        "display_options": None,
        "is_deleted_ldap": 0,
        "pdffont": None,
        "picture": None,
        "begin_date": None,
        "end_date": None,
        "keep_devices_when_purging_item": None,
        "privatebookmarkorder": None,
        "backcreated": None,
        "task_state": None,
        "layout": None,
        "palette": None,
        "set_default_requester": None,
        "lock_autolock_mode": None,
        "lock_directunlock_notification": None,
        "date_creation": "2020-02-27 16:37:38",
        "highcontrast_css": None,
        "plannings": None,
        "sync_field": None,
        "groups_id": 0,
        "users_id_supervisor": 0,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/User/18/Document_Item/"
            }
        ]
    },
    {
        "id": 19,
        "name": "filipe",
        "phone": "",
        "phone2": "",
        "mobile": "",
        "realname": "Souza",
        "firstname": "Filipe",
        "locations_id": 0,
        "language": None,
        "use_mode": 0,
        "list_limit": None,
        "is_active": 1,
        "comment": "",
        "auths_id": 0,
        "authtype": 1,
        "last_login": "2024-10-24 13:38:38",
        "date_mod": "2024-10-18 15:58:15",
        "date_sync": None,
        "is_deleted": 0,
        "profiles_id": 0,
        "entities_id": 0,
        "usertitles_id": 0,
        "usercategories_id": 0,
        "date_format": None,
        "number_format": None,
        "names_format": None,
        "csv_delimiter": None,
        "is_ids_visible": None,
        "use_flat_dropdowntree": None,
        "show_jobs_at_login": None,
        "priority_1": None,
        "priority_2": None,
        "priority_3": None,
        "priority_4": None,
        "priority_5": None,
        "priority_6": None,
        "followup_private": None,
        "task_private": None,
        "default_requesttypes_id": None,
        "password_forget_token": None,
        "password_forget_token_date": None,
        "user_dn": None,
        "registration_number": "",
        "show_count_on_tabs": None,
        "refresh_ticket_list": None,
        "set_default_tech": None,
        "personal_token": None,
        "personal_token_date": None,
        "api_token": None,
        "api_token_date": None,
        "cookie_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "cookie_token_date": "2024-10-18 15:58:15",
        "display_count_on_home": None,
        "notification_to_myself": None,
        "duedateok_color": None,
        "duedatewarning_color": None,
        "duedatecritical_color": None,
        "duedatewarning_less": None,
        "duedatecritical_less": None,
        "duedatewarning_unit": None,
        "duedatecritical_unit": None,
        "display_options": None,
        "is_deleted_ldap": 0,
        "pdffont": None,
        "picture": None,
        "begin_date": None,
        "end_date": None,
        "keep_devices_when_purging_item": None,
        "privatebookmarkorder": None,
        "backcreated": None,
        "task_state": None,
        "layout": None,
        "palette": None,
        "set_default_requester": None,
        "lock_autolock_mode": None,
        "lock_directunlock_notification": None,
        "date_creation": "2020-03-20 12:36:48",
        "highcontrast_css": None,
        "plannings": None,
        "sync_field": None,
        "groups_id": 0,
        "users_id_supervisor": 0,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/User/19/Document_Item/"
            }
        ]
    },
    {
        "id": 20,
        "name": "talita",
        "phone": "",
        "phone2": "",
        "mobile": "",
        "realname": "Souza",
        "firstname": "Talita",
        "locations_id": 0,
        "language": None,
        "use_mode": 0,
        "list_limit": None,
        "is_active": 1,
        "comment": "",
        "auths_id": 0,
        "authtype": 1,
        "last_login": "2024-11-08 10:52:44",
        "date_mod": "2024-11-07 14:42:50",
        "date_sync": None,
        "is_deleted": 0,
        "profiles_id": 0,
        "entities_id": 0,
        "usertitles_id": 0,
        "usercategories_id": 0,
        "date_format": None,
        "number_format": None,
        "names_format": None,
        "csv_delimiter": None,
        "is_ids_visible": None,
        "use_flat_dropdowntree": None,
        "show_jobs_at_login": None,
        "priority_1": None,
        "priority_2": None,
        "priority_3": None,
        "priority_4": None,
        "priority_5": None,
        "priority_6": None,
        "followup_private": None,
        "task_private": None,
        "default_requesttypes_id": None,
        "password_forget_token": None,
        "password_forget_token_date": None,
        "user_dn": None,
        "registration_number": "",
        "show_count_on_tabs": None,
        "refresh_ticket_list": None,
        "set_default_tech": 0,
        "personal_token": None,
        "personal_token_date": None,
        "api_token": None,
        "api_token_date": None,
        "cookie_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "cookie_token_date": "2024-11-07 14:42:50",
        "display_count_on_home": None,
        "notification_to_myself": None,
        "duedateok_color": None,
        "duedatewarning_color": None,
        "duedatecritical_color": None,
        "duedatewarning_less": None,
        "duedatecritical_less": None,
        "duedatewarning_unit": None,
        "duedatecritical_unit": None,
        "display_options": None,
        "is_deleted_ldap": 0,
        "pdffont": None,
        "picture": None,
        "begin_date": None,
        "end_date": None,
        "keep_devices_when_purging_item": None,
        "privatebookmarkorder": None,
        "backcreated": None,
        "task_state": None,
        "layout": None,
        "palette": None,
        "set_default_requester": None,
        "lock_autolock_mode": None,
        "lock_directunlock_notification": None,
        "date_creation": "2022-01-04 11:47:56",
        "highcontrast_css": None,
        "plannings": None,
        "sync_field": None,
        "groups_id": 0,
        "users_id_supervisor": 0,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/User/20/Document_Item/"
            }
        ]
    },
    {
        "id": 21,
        "name": "idelcio",
        "phone": "",
        "phone2": "",
        "mobile": "",
        "realname": "Santos",
        "firstname": "Idelcio",
        "locations_id": 0,
        "language": None,
        "use_mode": 0,
        "list_limit": None,
        "is_active": 1,
        "comment": "",
        "auths_id": 0,
        "authtype": 1,
        "last_login": None,
        "date_mod": "2022-07-12 09:06:02",
        "date_sync": None,
        "is_deleted": 0,
        "profiles_id": 0,
        "entities_id": 0,
        "usertitles_id": 0,
        "usercategories_id": 1,
        "date_format": None,
        "number_format": None,
        "names_format": None,
        "csv_delimiter": None,
        "is_ids_visible": None,
        "use_flat_dropdowntree": None,
        "show_jobs_at_login": None,
        "priority_1": None,
        "priority_2": None,
        "priority_3": None,
        "priority_4": None,
        "priority_5": None,
        "priority_6": None,
        "followup_private": None,
        "task_private": None,
        "default_requesttypes_id": None,
        "password_forget_token": None,
        "password_forget_token_date": None,
        "user_dn": None,
        "registration_number": "",
        "show_count_on_tabs": None,
        "refresh_ticket_list": None,
        "set_default_tech": None,
        "personal_token": None,
        "personal_token_date": None,
        "api_token": None,
        "api_token_date": None,
        "cookie_token": "",
        "cookie_token_date": None,
        "display_count_on_home": None,
        "notification_to_myself": None,
        "duedateok_color": None,
        "duedatewarning_color": None,
        "duedatecritical_color": None,
        "duedatewarning_less": None,
        "duedatecritical_less": None,
        "duedatewarning_unit": None,
        "duedatecritical_unit": None,
        "display_options": None,
        "is_deleted_ldap": 0,
        "pdffont": None,
        "picture": None,
        "begin_date": None,
        "end_date": None,
        "keep_devices_when_purging_item": None,
        "privatebookmarkorder": None,
        "backcreated": None,
        "task_state": None,
        "layout": None,
        "palette": None,
        "set_default_requester": None,
        "lock_autolock_mode": None,
        "lock_directunlock_notification": None,
        "date_creation": "2022-07-12 09:04:47",
        "highcontrast_css": 0,
        "plannings": None,
        "sync_field": None,
        "groups_id": 0,
        "users_id_supervisor": 0,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "UserCategory",
                "href": "https://glpi-teste.com.br/apirest.php/UserCategory/1"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/User/21/Document_Item/"
            }
        ]
    },
    {
        "id": 22,
        "name": "thiago",
        "phone": "",
        "phone2": "",
        "mobile": "",
        "realname": "Gondek",
        "firstname": "Thiago",
        "locations_id": 0,
        "language": None,
        "use_mode": 0,
        "list_limit": None,
        "is_active": 1,
        "comment": "",
        "auths_id": 0,
        "authtype": 1,
        "last_login": "2024-11-08 14:31:25",
        "date_mod": "2024-11-08 13:05:55",
        "date_sync": None,
        "is_deleted": 0,
        "profiles_id": 0,
        "entities_id": 0,
        "usertitles_id": 0,
        "usercategories_id": 1,
        "date_format": None,
        "number_format": None,
        "names_format": None,
        "csv_delimiter": None,
        "is_ids_visible": None,
        "use_flat_dropdowntree": None,
        "show_jobs_at_login": None,
        "priority_1": None,
        "priority_2": None,
        "priority_3": None,
        "priority_4": None,
        "priority_5": None,
        "priority_6": None,
        "followup_private": None,
        "task_private": None,
        "default_requesttypes_id": None,
        "password_forget_token": None,
        "password_forget_token_date": None,
        "user_dn": None,
        "registration_number": "",
        "show_count_on_tabs": None,
        "refresh_ticket_list": None,
        "set_default_tech": None,
        "personal_token": None,
        "personal_token_date": None,
        "api_token": None,
        "api_token_date": None,
        "cookie_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "cookie_token_date": "2024-11-08 13:05:55",
        "display_count_on_home": None,
        "notification_to_myself": None,
        "duedateok_color": None,
        "duedatewarning_color": None,
        "duedatecritical_color": None,
        "duedatewarning_less": None,
        "duedatecritical_less": None,
        "duedatewarning_unit": None,
        "duedatecritical_unit": None,
        "display_options": None,
        "is_deleted_ldap": 0,
        "pdffont": None,
        "picture": None,
        "begin_date": None,
        "end_date": None,
        "keep_devices_when_purging_item": None,
        "privatebookmarkorder": None,
        "backcreated": None,
        "task_state": None,
        "layout": None,
        "palette": None,
        "set_default_requester": None,
        "lock_autolock_mode": None,
        "lock_directunlock_notification": None,
        "date_creation": "2022-09-08 08:58:45",
        "highcontrast_css": None,
        "plannings": None,
        "sync_field": None,
        "groups_id": 0,
        "users_id_supervisor": 0,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "UserCategory",
                "href": "https://glpi-teste.com.br/apirest.php/UserCategory/1"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/User/22/Document_Item/"
            }
        ]
    },
    {
        "id": 23,
        "name": "paulo.santos",
        "phone": "",
        "phone2": "",
        "mobile": "",
        "realname": "Santos",
        "firstname": "Paulo",
        "locations_id": 0,
        "language": None,
        "use_mode": 0,
        "list_limit": None,
        "is_active": 1,
        "comment": "",
        "auths_id": 0,
        "authtype": 1,
        "last_login": None,
        "date_mod": "2022-09-27 10:40:30",
        "date_sync": None,
        "is_deleted": 0,
        "profiles_id": 0,
        "entities_id": 0,
        "usertitles_id": 0,
        "usercategories_id": 0,
        "date_format": None,
        "number_format": None,
        "names_format": None,
        "csv_delimiter": None,
        "is_ids_visible": None,
        "use_flat_dropdowntree": None,
        "show_jobs_at_login": None,
        "priority_1": None,
        "priority_2": None,
        "priority_3": None,
        "priority_4": None,
        "priority_5": None,
        "priority_6": None,
        "followup_private": None,
        "task_private": None,
        "default_requesttypes_id": None,
        "password_forget_token": None,
        "password_forget_token_date": None,
        "user_dn": None,
        "registration_number": "",
        "show_count_on_tabs": None,
        "refresh_ticket_list": None,
        "set_default_tech": None,
        "personal_token": None,
        "personal_token_date": None,
        "api_token": None,
        "api_token_date": None,
        "cookie_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "cookie_token_date": None,
        "display_count_on_home": None,
        "notification_to_myself": None,
        "duedateok_color": None,
        "duedatewarning_color": None,
        "duedatecritical_color": None,
        "duedatewarning_less": None,
        "duedatecritical_less": None,
        "duedatewarning_unit": None,
        "duedatecritical_unit": None,
        "display_options": None,
        "is_deleted_ldap": 0,
        "pdffont": None,
        "picture": None,
        "begin_date": None,
        "end_date": None,
        "keep_devices_when_purging_item": None,
        "privatebookmarkorder": None,
        "backcreated": None,
        "task_state": None,
        "layout": None,
        "palette": None,
        "set_default_requester": None,
        "lock_autolock_mode": None,
        "lock_directunlock_notification": None,
        "date_creation": "2022-09-27 10:40:30",
        "highcontrast_css": 0,
        "plannings": None,
        "sync_field": None,
        "groups_id": 0,
        "users_id_supervisor": 0,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/User/23/Document_Item/"
            }
        ]
    },
    {
        "id": 24,
        "name": "amanda",
        "phone": "",
        "phone2": "",
        "mobile": "",
        "realname": "Eduarda Oliveira Alves",
        "firstname": "Amanda",
        "locations_id": 0,
        "language": None,
        "use_mode": 0,
        "list_limit": None,
        "is_active": 1,
        "comment": "",
        "auths_id": 0,
        "authtype": 1,
        "last_login": "2023-10-03 09:44:15",
        "date_mod": "2023-10-03 09:44:15",
        "date_sync": None,
        "is_deleted": 0,
        "profiles_id": 0,
        "entities_id": 0,
        "usertitles_id": 0,
        "usercategories_id": 0,
        "date_format": None,
        "number_format": None,
        "names_format": None,
        "csv_delimiter": None,
        "is_ids_visible": None,
        "use_flat_dropdowntree": None,
        "show_jobs_at_login": None,
        "priority_1": None,
        "priority_2": None,
        "priority_3": None,
        "priority_4": None,
        "priority_5": None,
        "priority_6": None,
        "followup_private": None,
        "task_private": None,
        "default_requesttypes_id": None,
        "password_forget_token": None,
        "password_forget_token_date": None,
        "user_dn": None,
        "registration_number": "",
        "show_count_on_tabs": None,
        "refresh_ticket_list": None,
        "set_default_tech": None,
        "personal_token": None,
        "personal_token_date": None,
        "api_token": None,
        "api_token_date": None,
        "cookie_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "cookie_token_date": "2023-10-03 09:44:15",
        "display_count_on_home": None,
        "notification_to_myself": None,
        "duedateok_color": None,
        "duedatewarning_color": None,
        "duedatecritical_color": None,
        "duedatewarning_less": None,
        "duedatecritical_less": None,
        "duedatewarning_unit": None,
        "duedatecritical_unit": None,
        "display_options": None,
        "is_deleted_ldap": 0,
        "pdffont": None,
        "picture": None,
        "begin_date": None,
        "end_date": None,
        "keep_devices_when_purging_item": None,
        "privatebookmarkorder": None,
        "backcreated": None,
        "task_state": None,
        "layout": None,
        "palette": None,
        "set_default_requester": None,
        "lock_autolock_mode": None,
        "lock_directunlock_notification": None,
        "date_creation": "2023-10-03 09:27:00",
        "highcontrast_css": None,
        "plannings": None,
        "sync_field": None,
        "groups_id": 0,
        "users_id_supervisor": 0,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/User/24/Document_Item/"
            }
        ]
    },
    {
        "id": 25,
        "name": "maria.eduarda",
        "phone": "",
        "phone2": "",
        "mobile": "",
        "realname": "Eduarda Gondek dos Santos",
        "firstname": "Maria",
        "locations_id": 0,
        "language": None,
        "use_mode": 0,
        "list_limit": None,
        "is_active": 1,
        "comment": "",
        "auths_id": 0,
        "authtype": 1,
        "last_login": "2024-09-24 15:19:45",
        "date_mod": "2024-09-24 15:19:45",
        "date_sync": None,
        "is_deleted": 0,
        "profiles_id": 0,
        "entities_id": 0,
        "usertitles_id": 0,
        "usercategories_id": 0,
        "date_format": None,
        "number_format": None,
        "names_format": None,
        "csv_delimiter": None,
        "is_ids_visible": None,
        "use_flat_dropdowntree": None,
        "show_jobs_at_login": None,
        "priority_1": None,
        "priority_2": None,
        "priority_3": None,
        "priority_4": None,
        "priority_5": None,
        "priority_6": None,
        "followup_private": None,
        "task_private": None,
        "default_requesttypes_id": None,
        "password_forget_token": None,
        "password_forget_token_date": None,
        "user_dn": None,
        "registration_number": "",
        "show_count_on_tabs": None,
        "refresh_ticket_list": None,
        "set_default_tech": None,
        "personal_token": None,
        "personal_token_date": None,
        "api_token": None,
        "api_token_date": None,
        "cookie_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "cookie_token_date": "2024-09-24 15:19:45",
        "display_count_on_home": None,
        "notification_to_myself": None,
        "duedateok_color": None,
        "duedatewarning_color": None,
        "duedatecritical_color": None,
        "duedatewarning_less": None,
        "duedatecritical_less": None,
        "duedatewarning_unit": None,
        "duedatecritical_unit": None,
        "display_options": None,
        "is_deleted_ldap": 0,
        "pdffont": None,
        "picture": None,
        "begin_date": None,
        "end_date": None,
        "keep_devices_when_purging_item": None,
        "privatebookmarkorder": None,
        "backcreated": None,
        "task_state": None,
        "layout": None,
        "palette": None,
        "set_default_requester": None,
        "lock_autolock_mode": None,
        "lock_directunlock_notification": None,
        "date_creation": "2024-08-07 11:52:31",
        "highcontrast_css": None,
        "plannings": None,
        "sync_field": None,
        "groups_id": 0,
        "users_id_supervisor": 0,
        "links": [
            {
                "rel": "Entity",
                "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
            },
            {
                "rel": "Document_Item",
                "href": "https://glpi-teste.com.br/apirest.php/User/25/Document_Item/"
            }
        ]
    }
]

USER_SEARCH_RESPONSE = {
    '1': 'aramaral', 
    '2': 8, 
    '9': 'Tatianno', 
    '34': 'Alves'
}

USERS_SEARCH_RESPONSE = {
    'totalcount': 1, 
    'count': 1, 
    'sort': [1], 
    'order': ['ASC'], 
    'data': [
        {
            '1': 'aramaral', 
            '2': 8, 
            '9': 'Tatianno', 
            '34': 'Alves'
        }
    ], 
    'content-range': '0-0/1'
}