from enum import Enum


class AlertType(str, Enum):
    AIRFLOW_DB_STORAGE_UNUSUALLY_HIGH = "AIRFLOW_DB_STORAGE_UNUSUALLY_HIGH"
    DAG_DURATION = "DAG_DURATION"
    DAG_FAILURE = "DAG_FAILURE"
    DAG_SUCCESS = "DAG_SUCCESS"
    DAG_TIMELINESS = "DAG_TIMELINESS"
    DATA_PRODUCT_PROACTIVE_FAILURE = "DATA_PRODUCT_PROACTIVE_FAILURE"
    DATA_PRODUCT_PROACTIVE_SLA = "DATA_PRODUCT_PROACTIVE_SLA"
    DATA_PRODUCT_SLA = "DATA_PRODUCT_SLA"
    DEPRECATED_RUNTIME_VERSION = "DEPRECATED_RUNTIME_VERSION"
    JOB_SCHEDULING_DISABLED = "JOB_SCHEDULING_DISABLED"
    TASK_DURATION = "TASK_DURATION"
    TASK_FAILURE = "TASK_FAILURE"
    WORKER_QUEUE_AT_CAPACITY = "WORKER_QUEUE_AT_CAPACITY"

    def __str__(self) -> str:
        return str(self.value)
