

class FastaFileIterator:
    def __init__(self, fasta_path: str) -> None: ...
    def __iter__(self) -> FastaFileIterator: ...
    def __next__(self) -> tuple[str,str]: ...

class FastaStringIterator:
    def __init__(self, fasta_string: str | bytes) -> None: ...
    def __iter__(self) -> FastaStringIterator: ...
    def __next__(self) -> tuple[str,str]: ...

def parse_fasta(fasta_string: str | bytes) -> list[str]: ...
def parse_fasta_include_descriptions(fasta_string: str | bytes) -> tuple[list[str],list[str]]: ...
